### ISSUE TITLE
容器章节的进入容器问题

### ISSUE THREAD

**Issue by audeSt** [yeasy/docker_practice#101]
wget -P ~ https://github.com/yeasy/docker_practice/raw/master/_local/.bashrc_docker;

命令失效

文件已被移除

**Comment by yeasy** [comment]
Can u open it in your browser? Are u using a very old version of wget?

I checked, it's there, and it works with `wget` 1.18.

[.bashrc_docker](https://github.com/yeasy/docker_practice/raw/master/_local/.bashrc_docker)

**Comment by twang2218** [comment]
@audeSt 应该是 github 部分时候被墙的原因，这个链接可以访问。如果你那里有问题，你可以翻墙尝试。
