### ISSUE TITLE
无法访问此书url

### ISSUE THREAD

**Issue by kkxue** [yeasy/docker_practice#105]
访问：https://yeasy.gitbooks.io/docker_practice/content/
提示：
无法访问此网站
网址为 https://yeasy.gitbooks.io/docker_practice/content/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_NAME_RESOLUTION_FAILED

**Comment by kkc** [comment]
I can access this website, seems no problem for me

**Comment by yeasy** [comment]
Certainly this happens often.
Try using the backup [github link](https://github.com/yeasy/docker_practice/blob/master/SUMMARY.md).
Thanks!
