### ISSUE TITLE
win10的linux子系统安装docker有问题

### ISSUE THREAD

**Issue by binarywang** [yeasy/docker_practice#111]
系统内核应该是ubuntu 14.04的，有人验证过吗？
我在添加` /etc/apt/sources.list.d/docker.list`完之后，执行`sudo apt-get update`
最后几行报错：

> Fetched 11.8 MB in 41s (280 kB/s)
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/restricted/binary-amd64/Packages  Hash Sum mismatch
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/universe/binary-amd64/Packages  Hash Sum mismatch
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/multiverse/binary-amd64/Packages  Hash Sum mismatch
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.

然后导致执行` sudo apt-get install -y linux-image-extra-$(uname -r)`时报错：

> E: Unable to locate package linux-image-extra-3.4.0
> E: Couldn't find any package by regex 'linux-image-extra-3.4.0'

**Comment by yeasy** [comment]
Highly recommend you to use Docker on Linux OS.

**Comment by binarywang** [comment]
我知道问题原因了，是因为内核版本过低导致的，3.4.0这个版本不支持
