### ISSUE TITLE
ubuntu添加 Docker 的官方 apt 软件源时有问题

### ISSUE THREAD

**Issue by binarywang** [yeasy/docker_practice#113]
按照如下操作有问题，会报`-bash: /etc/apt/sources.list.d/docker.list: Permission denied`
不得已，已经通过手动vi完成

> 接下来就可以添加 Docker 的官方 apt 软件源了。通过下面命令创建  `/etc/apt/sources.list.d/docker.list` 文件，并写入源的地址内容。非 trusty 版本的系统注意修改为自己对应的代号。
> 
> ```
> $ sudo cat <<EOF > /etc/apt/sources.list.d/docker.list
> deb https://apt.dockerproject.org/repo ubuntu-trusty main
> EOF
> ```

**Comment by yeasy** [comment]
Try:
`sudo su` first, or `sudo bash -c "cat ..."`

**Comment by twang2218** [comment]
@binarywang 你可以看一下新写的 Ubuntu 安装 Docker 的章节：
<https://yeasy.gitbooks.io/docker_practice/content/install/ubuntu.html>

使用这个命令：

```bash
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
```

**Comment by binarywang** [comment]
感谢两位
