### ISSUE TITLE
'github-buttons' caused some trouble reading on mobile

### ISSUE THREAD

**Issue by twang2218** [yeasy/docker_practice#131]
If visit <https://yeasy.gitbooks.io/docker_practice/content/> from mobile, half of the page will be blank:

<img width="435" alt="2016-11-26 05 20 22" src="https://cloud.githubusercontent.com/assets/6299096/20639434/30123a70-b417-11e6-92c1-a0402d6f9657.png">

It is caused by `github-buttons` plugins.

**Comment by yeasy** [comment]
Yes, i noticed this, seems gitbook's css does not provide a good enough layout.

If we're lucky, there should be few mobile reader~

**Comment by twang2218** [comment]
I created a CSS layout to hide the github buttons on mobile page, I can read the book on mobile without the problem now. So, I'm closing this issue.
