### ISSUE TITLE
wrong path

### ISSUE THREAD

**Issue by rockcitystore** [yeasy/docker_practice#134]
https://yeasy.gitbooks.io/docker_practice/content/repository/local_repo.html

```
默认情况下，仓库会被创建在容器的 /tmp/registry 下。可以通过 -v 参数来将镜像文件存放在本地的指定路径。 例如下面的例子将上传的镜像放到 /opt/data/registry 目录。

$ sudo docker run -d -p 5000:5000 -v /opt/data/registry:/tmp/registry registry
```

should be `$ sudo docker run -d -p 5000:5000 -v /opt/data/registry:/var/lib/registry registry`

111https://docs.docker.com/registry/deploying/

**Comment by yeasy** [comment]
Thanks for the reporting, that might because the registry image has changed the path.

Would you like to submit a pr to correct this?

**Comment by twang2218** [comment]
Yes, the section should be updated to Registry v2. 

The `/tmp/registry` is for Docker registry v1, which has been deprecated for a year or so. And the `registry:latest` has been pointed to 2.x for several months. It's time to update the section, not only the link.

I have been updating the book from beginning, but haven't reached the registry section. You are welcome to help update this section, just create a PR for it. 😺
