### ISSUE TITLE
笔误 - image "Untagged 和 Deleted" 章节

### ISSUE THREAD

**Issue by chenshenyou** [yeasy/docker_practice#139]
有时候会发现所删除的层数和自己 docker pull 看到的层数不一样的源。
除了镜像依赖**意外**，还需要注意的是容器对镜像的依赖。如果有用这个镜像启动的
容器存在（即使容器没有运行），那么同样不可以删除这个镜像。

**Comment by yeasy** [comment]
Good catch, thanks!
