### ISSUE TITLE
english version?

### ISSUE THREAD

**Issue by sibelius** [yeasy/docker_practice#142]
docker practice looks awesome, any plans to translated it to english?

**Comment by twang2218** [comment]
Unfortunately, I don't think we have a plan here for translating the book into another language. 

Personally, my recent focus is on updating the contents of the book to match latest Docker's development, which has tons works to do,  and it's just beginning.

But the good thing about open sourced book is that it's welcome to fork and send pull request back for any feature you want to add. 😺

**Comment by yeasy** [comment]
@sibelius Thanks for your interests!
We now have the zh-tw language branch by volunteers, and would welcome for versions in other languages.
Thanks!
