### ISSUE TITLE
homebrew安装docker

### ISSUE THREAD

**Issue by cways** [yeasy/docker_practice#143]
希望在“macOS 操作系统安装 Docker”章节中加入“homebrew安装docker”的使用方式

**Comment by yeasy** [comment]
homebrew supports docker installation already?

If that's true, would welcome for a PR.

Thanks!

**Comment by twang2218** [comment]
嗯，Homebrew 已经支持 Docker for Mac，以及 Docker Toolbox。之前考虑过添加 `brew cask install docker` 的方式，但是不太清楚国内伟大的墙的影响会不会让这个命令执行失败，因此犹豫了一下没有加进来。

现在我创建了一个 PR 添加了 Homebrew Cask 安装 Docker for Mac 的方式。Docker Toolbox 在 Mac 上基本已不需要，所以没有添加到说明中去。

可以看一下还有什么需要改动的么。谢谢。

**Comment by yeasy** [comment]
@cways @twang2218 

Thanks for the enhancement!
