### ISSUE TITLE
这个地方落掉的词语

### ISSUE THREAD

**Issue by boxiaozhi** [yeasy/docker_practice#156]
https://yeasy.gitbooks.io/docker_practice/content/basic_concept/repository.html

第三段
> 一般而言，一个仓库包含的是同一个软件的不同版本的镜像，而标签则用于对应于软件的的不同版本。

对于软件的什么版本呢？

**Comment by yeasy** [comment]
The versions/distributions of the software.
e.g., ubuntu have several releases like 14.04 or 16.04.

**Comment by boxiaozhi** [comment]
多了一个“的”字，一下子没反应过来。已经明白了。谢谢

**Comment by twang2218** [comment]
@boxiaozhi 哦，不好意思，这里是我多敲了一个“的”字，而且可能表达容易产生混淆，我修改了一下： https://github.com/yeasy/docker_practice/pull/157
