### ISSUE TITLE
book.json 缺少plugins

### ISSUE THREAD

**Issue by CharlesSong** [yeasy/docker_practice#159]
全部的插件配置应该是：
`
"plugins":` [
    "image-captions",
    "github-buttons",
    "fontsettings",
    "livereload",
    "highlight",
    "lunr",
    "sharing",
    "search" 
  ]
`

**Comment by yeasy** [comment]
aha, do we really need those ones like fontsettings and livereload?

otherwise, too many plugins only slow down the compiling/loading, i guess.
