### ISSUE TITLE
The wrong words

### ISSUE THREAD

**Issue by Howld** [yeasy/docker_practice#160]
Link: https://yeasy.gitbooks.io/docker_practice/content/image/dockerfile/env.html
✘-2 ~/Downloads/docker_practice [master|✔] 
16:40 $ grep '使用使用' -r *
image/dockerfile/env.md:这个指令很简单，就是设置环境变量而已，无论是后面的其它指令，如 `RUN`，还是运行时的应用，都可以直接使用使用这里定义的环境变量。

Link: https://yeasy.gitbooks.io/docker_practice/content/image/other.html
image/other.md:导入成功后，我们可以用 `docker ps` 看到这个导入的镜像：

**Comment by yeasy** [comment]
thanks, would u like to help fix these typos with a pr?

**Comment by Howld** [comment]
What's mean pr? Public relations?

**Comment by twang2218** [comment]
PR => Pull Request

**Comment by stenote** [comment]
I think you could close this issue now. @yeasy
