### ISSUE TITLE
Recommend to use a plugin for generating "Treeview" for each article in the book

### ISSUE THREAD

**Issue by aleen42** [yeasy/docker_practice#166]
[**gitbook-treeview**](https://github.com/aleen42/gitbook-treeview) is a Gitbook plugin designed for generating structures for articles of a book. As the following picture shown, the main structure of a whole article has been clearly shown before contents, and each title has also been directed to a corresponding part. Docker Practice is a large book, which has integrated with Gitbook, and I hope that the plugin can helps to enhance readability. If you like it, I hope you can star my project too, and thanks for your appreciations. As for the picture, it's an article named ["Asynchronous Programming"](https://aleen42.gitbooks.io/personalwiki/content/Programming/JavaScript/async_programming/async_programming.html) in my personal wiki book.

![gitbook treeview](https://cdn.rawgit.com/aleen42/https-resources/master/gitbook_treeview_preview.png)

**Comment by yeasy** [comment]
@aleen42 
interesting, would u like to give a sample of the result by enabling the plugin?

**Comment by aleen42** [comment]
Configure the file `book.json` of your book by adding two items into corresponding objects `plugins`, and `pluginsConfig`. And then, rebuild your book to apply it.

- `copyright`: If you don't want to show the copyright info, just set it as empty string.
- `minHeaderCount`: means if the amount of headers is lower than this value, the "Treeview" won't be generated.
- `minHeaderDeep`: means if the depth of headers is lower than this value, the "Treeview" won't also be generated.

```js
{
	"plugins": [
		/** ... */
		"page-treeview",
		/** ... */
	],
	"pluginsConfig": {
		/** ... */,
		"page-treeview": {
			"copyright": "Copyright &#169; aleen42",
			"minHeaderCount": "2",
			"minHeaderDeep": "2"
		},
		/** ... */
	}
}
```

**Comment by yeasy** [comment]
Aha, i just noticed u're the plugin author.
would u like to submit a pr? :)

**Comment by aleen42** [comment]
@yeasy Aha, check the pull request [here](https://github.com/yeasy/docker_practice/pull/167). Thanks for your using.

**Comment by yeasy** [comment]
Merged, thanks!
