### ISSUE TITLE
onbuild不成功

### ISSUE THREAD

**Issue by kylezhang** [yeasy/docker_practice#168]
您好，根据[onbuild](https://github.com/yeasy/docker_practice/blob/master/image/dockerfile/onbuild.md)章节的内容，不能成功build镜像，具体如下；
- 有`ONBUILD`的Dockerfile内容如下：
```
FROM node:slim
RUN "mkdir /app"
WORKDIR /app
ONBUILD COPY ./package.json /app
ONBUILD RUN [ "npm", "install" ]
ONBUILD COPY . /app/
CMD [ "npm", "start" ]
```
- 对其进行docker build时出现如下error：
![image](https://cloud.githubusercontent.com/assets/3679798/25330634/ea6efb9a-2912-11e7-9c68-7aced19e3348.png)

**Comment by kylezhang** [comment]
# 继续发现问题
- 在上面修改正确的基础上，再次执行只有一行命令的Dockerfile，出现下如下error；
- 只用一行指令的Dockerfile内容：
`FROM kyle-node`

![image](https://cloud.githubusercontent.com/assets/3679798/25331899/38578972-2917-11e7-92eb-93826f68dc34.png)

**Comment by wujr5** [comment]
@kylezhang 这位兄台，首先可能是你 `npm install` 的目录不对，其次从截图上所看到的信息，貌似不是error ？

**Comment by kylezhang** [comment]
@wujr5 关于你说`npm install`目录不对，难道是我的理解错了，这是的我的[test项目的test002](https://github.com/kylezhang/Docker/tree/master/test002)，
- 大体的目录结构如下：
![image](https://cloud.githubusercontent.com/assets/3679798/25366527/dd9b6c74-29a2-11e7-80bf-8816f6d7e84a.png)

- `package.json`文件和只有一行指令的`Dockerfile`位于同一目录，具体请参考我[代码仓库](https://github.com/kylezhang/Docker/tree/master/test002)

**Comment by twang2218** [comment]
@kylezhang `ONBUILD` 并不是在你使用当前 `Dockerfile` 执行 `docker build` 时所执行的命令，请再看一下章节中的说明。`ONBUILD` 是指当你构建继承自该镜像的镜像时首先执行的命令。

举例而言，如果你在一个 `Dockerfile` 中包含有 `ONBUILD` 命令，当你使用该 `Dockerfile` 进行 `docker build` 时，并不会执行 `ONBUILD` 指令。假设你构建镜像的名为 `mysoft`，那么当你继承该镜像是，比如在另一个 `Dockerfile` 中使用 `FROM mysoft` 之时，这个新的镜像 `docker build` 时，才会运行 `mysoft` 镜像所使用的 `Dockerfile` 中的 `ONBUILD` 指令。

**Comment by yeasy** [comment]
Thanks for all the clarification.

I think it's clear to close the issue now.
