### ISSUE TITLE
Docker活动图

### ISSUE THREAD

**Issue by Ansafari** [yeasy/docker_practice#172]
用什么软件绘制的？

**Comment by yeasy** [comment]
which one?

**Comment by Ansafari** [comment]
[](https://yeasy.gitbooks.io/docker_practice/content/appendix/_images/cmd_logic.png)

**Comment by Ansafari** [comment]
![pic](https://yeasy.gitbooks.io/docker_practice/content/appendix/_images/cmd_logic.png)

**Comment by yeasy** [comment]
Sorry, i forgot.
Is it this one? https://github.com/yeasy/docker_practice/tree/master/appendix/_images/cmd_logic.graffle

**Comment by Ansafari** [comment]
OmniGraffle.
Thank you.
