### ISSUE TITLE
CommandError: 'docker-composeexample' is not a valid project name. Please use only numbers, letters and underscores.

### ISSUE THREAD

**Issue by inernoro** [yeasy/docker_practice#174]
地址: https://yeasy.gitbooks.io/docker_practice/content/compose/django.html
运行错误:CommandError: 'docker-composeexample' is not a valid project name. Please use only numbers, letters and underscores.

**Comment by yeasy** [comment]
Is this one work?

https://github.com/yeasy/docker_practice/blob/master/compose/django.md
