### ISSUE TITLE
`kernel_capability.md`中的链接失效

### ISSUE THREAD

**Issue by wenfengshi** [yeasy/docker_practice#176]
`docker_practice/security/kernel_capability.md`中的链接失效

原文如下：

> 默认情况下，Docker采用 [白名单](https://github.com/docker/docker/blob/master/daemon/execdriver/native/template/default_template.go) 机制，禁用 [必需功能](https://github.com/docker/docker/blob/master/daemon/execdriver/native/template/default_template.go) 之外的其它权限。
当然，用户也可以根据自身需求来为 Docker 容器启用额外的权限。

**Comment by yeasy** [comment]
@wenfengshi thanks, would u like to create a pr to fix?
thanks!
