### ISSUE TITLE
利用 commit 理解镜像构成—文章图片地址错误

### ISSUE THREAD

**Issue by leotian** [yeasy/docker_practice#178]
https://yeasy.gitbooks.io/docker_practice/content/image/commit.html 
![image](https://user-images.githubusercontent.com/10192886/27618909-8ac9e6fc-5bf1-11e7-9c48-79f7ceea5bcf.png)
直接用浏览器访问的话，我们会看到默认的 Nginx 欢迎页面。后面跟着的图裂了。

**Comment by yeasy** [comment]
Thanks for the report!
Seems the image path is broken, would u like to help fix with a pr?
