### ISSUE TITLE
访问仓库：私有仓库的说明步骤混乱

### ISSUE THREAD

**Issue by robbertzhang** [yeasy/docker_practice#180]
哪些步骤是先后顺序，哪些步骤是并列顺序等等。整个来说就是逻辑不清晰，步骤顺序混乱，对于没用过docker的来说，完全不知道具体怎么操作。我只能又在网上另外搜索搭建私有仓库

**Comment by khs1994** [comment]
搭建私有仓库这里我根据自己的实际操作，可以进行内容的增加。

**Comment by yeasy** [comment]
@khs1994 feel free to help fix, thanks!

**Comment by khs1994** [comment]
删除手动安装，通过配置文件，和挂载路径可以很简单的实现私有仓库。

**Comment by khs1994** [comment]
尽可能简化步骤，其他高级设置请阅读官方文档。

https://docs.docker.com/registry/deploying/#deploy-your-registry-using-a-compose-file

**Comment by khs1994** [comment]
删除配置一节，已有的配置文件已经不符合 v2 规范。

**Comment by khs1994** [comment]
`v0.9-rc3` 增加介绍私有仓库高级功能，访问控制、TLS

**Comment by khs1994** [comment]
`Nginx 代理` 暂不加入，链接到官方文档。
