### ISSUE TITLE
Add English version of this document

### ISSUE THREAD

**Issue by skoirala** [yeasy/docker_practice#181]
I am new to docker. I have been learning it mostly by reading articles in web and trying them on my own. I came across this github page and it looks really easy for newcomer to understand nits and grits. I use Google translate to translate Chinese, I can understand almost everything. But, I think it would be good if there is English translation for this. I want to make a feature request for translating these document to English.

**Comment by yeasy** [comment]
Sure, this is welcome, @skoirala 

We already have branches with other languages, pls feel free to create a new branch for English version. Thanks!

**Comment by skoirala** [comment]
I am in holiday right now. I can start with English version of this soon after my holidays. Closing this for now.
