### ISSUE TITLE
QQ群号码错误

### ISSUE THREAD

**Issue by zhukangfeng** [yeasy/docker_practice#189]
QQ 群 X （可加）：366203473 这个群号码搜索后的结果是音乐群。是否写错号码了？

**Comment by yeasy** [comment]
pls join IX. Not sure what happens...

**Comment by zhukangfeng** [comment]
Ok, thx

**Comment by khs1994** [comment]
@yeasy  QQ群加入申请，一直没有回应

**Comment by yeasy** [comment]
@khs1994 which one is ur num? 1****9?

**Comment by khs1994** [comment]
加入 571502246 没有回应，3232****

**Comment by khs1994** [comment]
最新的群已满

**Comment by yeasy** [comment]
不按照要求格式更新群名片的可以踢出。

**Comment by khs1994** [comment]
再新建一个吧，没必要要求群名片
