### ISSUE TITLE
删除虚悬镜像的指令在 docker 17.05.x 失效

### ISSUE THREAD

**Issue by gumutianqi** [yeasy/docker_practice#190]
![2017-08-30 11 04 50](https://user-images.githubusercontent.com/1057589/29853525-19f179a0-8d73-11e7-92d3-0cb62df0bd1f.png)

**Comment by yeasy** [comment]
Can u post the image results?
suspect there's no matched result.

**Comment by khs1994** [comment]
根据我的测试，因为没有 虚悬镜像 所以 `docker rmi $(docker images -q -f dangling=true)`中的子命令`docker images -q -f dangling=true`返回结果为空，`docker rmi`也就没有参数输入。所以报错，如果不是这个原因，请再次交流

**Comment by khs1994** [comment]
请贴上 `$ docker images` 执行结果图

**Comment by gumutianqi** [comment]
如下图，有三个构建中途失败的镜像

![image](https://user-images.githubusercontent.com/1057589/30014328-399ad648-917e-11e7-8bf1-ea691c4f76b3.png)

**Comment by khs1994** [comment]
`docker images -q -f dangling=true`这个命令的执行结果呢

**Comment by gumutianqi** [comment]
结果和上面发的结果是一样的，提示缺少参数

![image](https://user-images.githubusercontent.com/1057589/30019903-ac89e0ca-9194-11e7-9eb2-f15fceabb410.png)

**Comment by khs1994** [comment]
执行 `$ docker image prune` 试试

**Comment by khs1994** [comment]
参考

https://docs.docker.com/engine/reference/commandline/image_prune/

https://segmentfault.com/a/1190000007822648

**Comment by khs1994** [comment]
删除镜像的内容可以采用新的 image 子命令

**Comment by yeasy** [comment]
@khs1994 thanks! Those command evolve quickly!
