### ISSUE TITLE
进入容器一节无法使用，可能已经对新版本 docker 失效

### ISSUE THREAD

**Issue by gumutianqi** [yeasy/docker_practice#191]
`docker version 17.05.0 ce`
使用了文档里面描述的` .bashrc_docker`脚本后，执行响应的获取 docker PID 的命令失败，docker-enter 也无法使用，如下图：

![2017-08-30 11 06 37](https://user-images.githubusercontent.com/1057589/29853622-96365f76-8d73-11e7-99c4-590d68e1300f.png)

**Comment by gumutianqi** [comment]
问题已经解决，新版本的 docker 已经可以官方的命令 docker exec 了，建议更新文档；

```
docker exec CONTAINER_NAME /bin/bash
```

**Comment by yeasy** [comment]
@gumutianqi thanks, would u like to highlight this change (with since version number) through a pr?
