### ISSUE TITLE
安装 Docker 一节建议参照官方文档进行更新。

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#192]
建议区分 docker-ce  和 docker-ee 的安装步骤。
`$ sudo apt-get install docker-engine`也比较陈旧了。
`$ sudo apt-get install docker-ce`

**Comment by yeasy** [comment]
Thanks, @khs1994 would u like to make a pr?

**Comment by khs1994** [comment]
将 Ubuntu 与 Debian 分开可以吗

**Comment by khs1994** [comment]
我正在准备这部分的修改，内容参照最新的官方文档
有几个问题与大家探讨以下
* Docker CE 不再支持 Ubuntu 12.04 ，准备删去这部分内容
* 删去脚本安装方法，专业人员会自己看官方文档，小白使用脚本安装，过程中出现错误不易排查。
* 由于国内网络问题，先介绍国内源，再介绍官方源。
* Debian 根据我自己的实际操作，增加 树莓派（armhf 32位） 安装 Docker 部分 ,民间的树莓派64位系统，暂时安装不了 Docker

**Comment by khs1994** [comment]
增加 Windows PC 安装步骤

**Comment by yeasy** [comment]
Thanks, pls help close the issue after merged.
