### ISSUE TITLE
你的书缺乏一个统一的排版规则，这样只会越写越难看

### ISSUE THREAD

**Issue by ghost** [yeasy/docker_practice#20]
读了你的书，发现排版的问题很大。

建议参考：

https://github.com/sparanoid/chinese-copywriting-guidelines

在书写的时候尽量参考一个规范，而且在接受 pull request 的时候，也要用相同的规范去检查这些 pull request.

**Comment by yeasy** [comment]
We will add more guideline in content format, close this suggestion first, thanks!
