### ISSUE TITLE
附录五 增加中文资源链接 同时欢迎大家在这里提交链接，根据内容质量，增加到附录中。

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#200]
建议增加 

Docker变更日志中文版 
https://github.com/allencloud/docker-changelog-chinese

Dockerfile 最佳实践 中文翻译
http://blog.csdn.net/candcplusplus/article/details/53366024

**Comment by khs1994** [comment]
部分链接失效，或官方进行了跳转，请更新

**Comment by yeasy** [comment]
Thanks, and would prefer to add the official changelog link.

**Comment by khs1994** [comment]
我觉得本书主要面向中文读者，增加一些翻译资料未尝不可。
