### ISSUE TITLE
增加 docker image | volume | container 等 Docker 子命令

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#203]
https://segmentfault.com/a/1190000007822648

**Comment by yeasy** [comment]
Thanks, would u like to help propose a PR?

**Comment by khs1994** [comment]
您对这几个命令怎么看，有没有可能未来会逐步代替 `docker run` 、`docker ps` 等命令。

**Comment by yeasy** [comment]
Let's add them first, users will choose what's correct!
