### ISSUE TITLE
离线阅读：增加 docker run 阅读方式

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#216]
### your OS

* [ ] Linux

   * [ ] CentOS 7

   * [ ] Ubuntu 14.04

   * [ ] Ubuntu 16.04

   * [ ] Ubuntu 17.04

   * [ ] Ubuntu 17.10

   * [ ] CoreOS

   * [ ] Debian 7.7

   * [ ] Debian 8

   * [ ] Debian 9

* [x] macOS

* [ ] Windows 10

### Docker CE Version

* [x] 17.10 edge

* [ ] 17.09 stable

* [ ] 1.13.0

* [ ] 1.8.0

### Problem description

```bash
$ docker run -v $PWD:/srv/gitbook-src ...
````

用户打开 `127.0.0.1:4000` 即可离线阅读本书。

**Comment by khs1994** [comment]
https://github.com/khs1994/docker_practice_gitbook_image

**Comment by khs1994** [comment]
```bash
$ git clone --depth=1 https://github.com/yeasy/docker_practice.git

$ cd docker_practice

$ docker run -it --rm \
    -v $PWD:/srv/gitbook-src \
    -p 4000:4000 \
    khs1994/docker_practice
```

Then, open `127.0.0.1:4000`

**Comment by khs1994** [comment]
Please fork my repo (https://github.com/khs1994/docker_practice_gitbook_image) then change `khs1994` to `yeasy`。then build this image in docker hub

**Comment by khs1994** [comment]
根目录添加 `docker-compose.yml`

直接使用 `docker-compose up` 来启动容器，开启离线阅读

**Comment by khs1994** [comment]
在根目录增加 Dockerfile ,docker hub 关联本仓库开始构建

**Comment by khs1994** [comment]
请 build 镜像！

**Comment by khs1994** [comment]
我自己在 腾讯云容器服务开了一个命名空间。国内用户 pull ,国外用户 build

**Comment by yeasy** [comment]
What do u need me to help?

**Comment by khs1994** [comment]
您知道 Docker Cloud 吗？可以使用 Docker Cloud 构建镜像吗？它有自动测试的功能，这样做到了检查 PR(构建 gitbook 是否成功)

**Comment by khs1994** [comment]
https://cloud.docker.com

**Comment by khs1994** [comment]
![2017-11-23 10 09 41](https://user-images.githubusercontent.com/16733187/33156620-806ac8fc-d036-11e7-9552-08c035c0cc0f.png)

delete image from docker hub,then new image from docker cloud

Builds->Configure Automated Builds

Please open AUTOTEST

**Comment by khs1994** [comment]
https://docs.docker.com/docker-cloud/builds/automated-testing/

**Comment by khs1994** [comment]
您只要关联仓库，然后像我图中那样设置就行

**Comment by yeasy** [comment]
Nice idea, i've migrate to docker cloud now: https://cloud.docker.com/app/yeasy/repository/docker/yeasy/docker_practice/builds

**Comment by khs1994** [comment]
Add Wiki
