### ISSUE TITLE
年底发布 v0.9.0 基于 Docker CE v17.09 Stable

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#218]
### your OS

* [ ] Linux

   * [ ] CentOS 7

   * [ ] Ubuntu 14.04

   * [ ] Ubuntu 16.04

   * [ ] Ubuntu 17.04

   * [ ] Ubuntu 17.10

   * [ ] CoreOS

   * [ ] Debian 7.7

   * [ ] Debian 8

   * [ ] Debian 9

* [x] macOS

* [ ] Windows 10

### Docker CE Version

* [x] 17.10 edge

* [ ] 17.09 stable

* [ ] 1.13.0

* [ ] 1.8.0

### Problem description

年底发布 v0.9.0 基于 Docker CE v17.11 edge

**Comment by khs1994** [comment]
`k8s` `mesos`  `安全` `底层实现` 不太了解，不进行更新。

**Comment by yeasy** [comment]
That's fine, one milestone is after another.
