### ISSUE TITLE
[离线阅读]功能反馈如果你对离线阅读功能有任何疑问，请在这里留言。

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#220]
### your OS

* [ ] Linux

   * [ ] CentOS 7

   * [ ] Ubuntu 14.04

   * [ ] Ubuntu 16.04

   * [ ] Ubuntu 17.04

   * [ ] Ubuntu 17.10

   * [ ] CoreOS

   * [ ] Debian 7.7

   * [ ] Debian 8

   * [ ] Debian 9

* [x] macOS

* [ ] Windows 10

### Docker CE Version

* [x] 17.11 edge

* [ ] 17.09 stable

* [ ] 1.13.0

* [ ] 1.8.0

### Problem description

请大家积极反馈基于 Docker 的离线阅读。

**Comment by yeasy** [comment]
Would suggest to create a page at wiki to collect feedbacks.

Issues should be closed after done.

**Comment by khs1994** [comment]
拉取速度慢

**Comment by yeasy** [comment]
U mean docker image pull?

I feel the speed was improved a lot recently, that's better.

And these feedback collection page can be put on this repo's wiki: https://github.com/yeasy/docker_practice/wiki
