### ISSUE TITLE
CoreOS fleet 已经废弃

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#222]
### your OS

* [x] Linux

   * [x] CentOS 7

   * [ ] Ubuntu 14.04

   * [ ] Ubuntu 16.04

   * [ ] Ubuntu 17.04

   * [ ] Ubuntu 17.10

   * [ ] CoreOS

   * [ ] Debian 7.7

   * [ ] Debian 8

   * [ ] Debian 9

* [ ] macOS

* [ ] Windows 10

### Docker CE Version

* [x] 17.11 edge

* [ ] 17.09 stable

* [ ] 1.13.0

* [ ] 1.8.0

### Problem description

https://coreos.com/blog/migrating-from-fleet-to-kubernetes.html

https://github.com/yeasy/docker_practice/blob/master/coreos/intro_tools.md

**Comment by khs1994** [comment]
@zhangbaitong

你能更新 CoreOS 这一部分吗？

**Comment by yeasy** [comment]
Will keep this open for a while, to see if anyone volunteer to update this content.
Thanks!

**Comment by khs1994** [comment]
移除 fleet ,CoreOS 相关内容暂时不增加。
