### ISSUE TITLE
[排版规范] # 与标题之间必须有空格

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#223]
### your OS

* [x] Linux

   * [x] CentOS 7

   * [ ] Ubuntu 14.04

   * [ ] Ubuntu 16.04

   * [ ] Ubuntu 17.04

   * [ ] Ubuntu 17.10

   * [ ] CoreOS

   * [ ] Debian 7.7

   * [ ] Debian 8

   * [ ] Debian 9

* [ ] macOS

* [ ] Windows 10

### Docker CE Version

* [x] 17.11 edge

* [ ] 17.09 stable

* [ ] 1.13.0

* [ ] 1.8.0

### Problem description

`# 与标题之间必须有空格`

不然 GitHub 不能识别标题

**Comment by yeasy** [comment]
how about we add some "写作规范" rules for new contributors?

**Comment by khs1994** [comment]
已经说明 写作规范。
