### ISSUE TITLE
归档 0.8 版本，0.9 全部更新为Docker 17.09 Stable 官方推荐的命令、使用方法等。Docker 1.13.0 以下版本请查看 docker-legacy  分支

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#231]
### your OS

* [x] Linux

   * [x] CentOS 7

   * [ ] Ubuntu 14.04

   * [ ] Ubuntu 16.04

   * [ ] Ubuntu 17.04

   * [ ] Ubuntu 17.10

   * [ ] CoreOS

   * [ ] Debian 7.7

   * [ ] Debian 8

   * [ ] Debian 9

* [ ] macOS

* [ ] Windows 10

### Docker CE Version

* [x] 17.11 edge

* [ ] 17.09 stable

* [ ] 1.13.0

* [ ] 1.8.0

### Problem description

0.9 版本基于 Docker v17.12 Stable (未发布)

**Comment by khs1994** [comment]
我提交内容之前的为 `0.8` 版本，之后为 `0.9`。

**Comment by yeasy** [comment]
Would suggest rename `bump-0.8` branch to `docker-legacy`.

**Comment by khs1994** [comment]
OK

**Comment by khs1994** [comment]
0.9-rc1 基本完成

这几天正在考虑更新 `CoreOS` 旧的 `cloud-config.yaml` 安装方法已经废弃，采用新的 `Ignition` 来配置安装
