### ISSUE TITLE
如何区分 Docker Swarm 、swarm mode、 SwarmKit

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#233]
### your OS

* [x] Linux

   * [x] CentOS 7

   * [ ] Ubuntu 14.04

   * [ ] Ubuntu 16.04

   * [ ] Ubuntu 17.04

   * [ ] Ubuntu 17.10

   * [ ] CoreOS

   * [ ] Debian 7.7

   * [ ] Debian 8

   * [ ] Debian 9

* [ ] macOS

* [ ] Windows 10

### Docker CE Version

* [x] 17.11 edge

* [ ] 17.09 stable

* [ ] 1.13.0

* [ ] 1.8.0

**Comment by khs1994** [comment]
Docker Swarm 是不是可以考虑删除了

**Comment by yeasy** [comment]
The term Docker swarm is still popular, we may add some content to intro the history.

e.g.,

swarm mode (previous known as docker swarm), blabla...

**Comment by khs1994** [comment]
You are viewing docs for legacy standalone Swarm. These topics describe standalone Docker Swarm. In Docker 1.12 and higher, Swarm mode is integrated with Docker Engine. **Most users should use integrated Swarm mode** — a good place to start is Getting started with swarm mode, Swarm mode CLI commands, and the Get started with Docker walkthrough). Standalone Docker Swarm is not integrated into the Docker Engine API and CLI commands.

**Comment by yeasy** [comment]
Yes, i know that.
We can focus at the swarm mode in the latest content certainly.
Close the issue first.
