### ISSUE TITLE
更新 Compose 3 文件格式

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#238]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] CoreOS
   * [ ] Debian 8
   * [ ] Debian 9
* [ ] MacOS
* [ ] Windows 10
* [ ] Others (Pls describe below)

### Docker Version

* [x] 17.11 edge
* [ ] 17.09 stable
* [ ] 1.13.0
* [ ] Before 1.13.0

### Problem Description

3 文件格式 废弃参数
https://docs.docker.com/compose/compose-file/compose-versioning/#version-3

**Comment by yeasy** [comment]
if v2 is not deprecated soon, we can take it easy.

I feel v3 is still not that mature without full features support.

**Comment by khs1994** [comment]
v3 增加 `deploy` 与 swarm mode 能更好的结合
