### ISSUE TITLE
操作系统 一节不应该包含 CoreOS，其他都是 Docker 镜像，CoreOS 是运行 Docker 的 Linux 发行版

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#242]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] CoreOS
   * [ ] Debian 8
   * [ ] Debian 9
* [ ] MacOS
* [ ] Windows 10
* [ ] Others (Pls describe below)

### Docker Version

* [x] 17.11 edge
* [ ] 17.09 stable
* [ ] 1.13.0
* [ ] Before 1.13.0

### Problem Description

删除 操作系统 一节中的 CoreOS，移动到 CoreOS 一节。

**Comment by yeasy** [comment]
OK.
