### ISSUE TITLE
Stars 翻译为 收藏数

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#245]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] CoreOS
   * [ ] Debian 8
   * [ ] Debian 9
* [ ] MacOS
* [ ] Windows 10
* [ ] Others (Pls describe below)

### Docker Version

* [x] 17.11 edge
* [ ] 17.09 stable
* [ ] 1.13.0
* [ ] Before 1.13.0

### Problem Description

https://github.com/yeasy/docker_practice/blob/master/repository/dockerhub.md

这里翻译成了评价数量

**Comment by khs1994** [comment]
收藏数 表示关注程度

pull 数量才能表示受欢迎程度

**Comment by yeasy** [comment]
+1!

**Comment by khs1994** [comment]
https://github.com/yeasy/docker_practice/blob/master/repository/dockerhub.md
