### ISSUE TITLE
docker_practice 在 MacOS上跑不起来

### ISSUE THREAD

**Issue by tldzyx** [yeasy/docker_practice#252]
* [x] Have u googled the problem? If no, pls do that first!

### Environment

* [ ] Linux
   * [ ] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] CoreOS
   * [ ] Debian 8
   * [ ] Debian 9
* [x] MacOS
* [ ] Windows 10
* [ ] Others (Pls describe below)

### Docker Version

* [ ] 17.11 Edge
* [x] 17.09 Stable
* [ ] 1.13.0
* [ ] Before 1.13.0

### Problem Description

根据[教程](https://github.com/yeasy/docker_practice/wiki/%E7%A6%BB%E7%BA%BF%E9%98%85%E8%AF%BB%E5%8A%9F%E8%83%BD%E8%AF%A6%E8%A7%A3)跑docker_practice，windows和linux都没问题，但是MacOS跑不起来。

![image](https://user-images.githubusercontent.com/5987706/33251630-2ca0b94e-d373-11e7-81ce-a310c78b4722.png)

**Comment by khs1994** [comment]
pull 最新镜像

```bash
$ docker image ls

$ docker-compose pull 
$ docker-compose up
```

**Comment by khs1994** [comment]
若有问题再留言

**Comment by khs1994** [comment]
你在 Windows 下使用离线阅读没问题吗？

我测试了一下，有 “一大堆” 问题。

**Comment by tldzyx** [comment]
Windows下我没碰到，不过也就跑了1天，后面发现目录映射比较蛋疼，原理上也是跑个虚拟机，就都换到ubuntu虚拟机里面跑docker了， 目前没遇到问题。

**Comment by khs1994** [comment]
问题已经解决了。详情查看 wiki
