### ISSUE TITLE
按照文档要求无法通过docker-compose up 启动容器

### ISSUE THREAD

**Issue by y0299** [yeasy/docker_practice#254]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [ ] Linux
   * [ ] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] CoreOS
   * [ ] Debian 8
   * [ ] Debian 9
* [ ] macOS
* [x] Windows 10
* [ ] Others (Pls describe below)

### Docker Version

* [] 17.11 Edge
* [x] 17.09 Stable
* [ ] 1.13.0
* [ ] Before 1.13.0

### Problem Description

λ docker-compose.exe pull
Pulling docker_practice (yeasy/docker_practice:latest)...
latest: Pulling from yeasy/docker_practice
Digest: sha256:e438858dfddda5297bb9abe560483f080e6a01cfbbed15a5dfb7fb428e5d6984
Status: Image is up to date for yeasy/docker_practice:latest

D:\docker_practice (master)
λ docker-compose.exe up
Starting dockerpractice_docker_practice_1 ...
Starting dockerpractice_docker_practice_1 ... done
Attaching to dockerpractice_docker_practice_1
docker_practice_1  | Live reload server started on port: 35729
docker_practice_1  | Press CTRL+C to quit ...
docker_practice_1  |
docker_practice_1  |
_**docker_practice_1  | FileNotFoundError: No "README" file (or is ignored)
dockerpractice_docker_practice_1 exited with code 0**_

D:docker_practice (master)
λ
D:docker_practice (master)
λ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by khs1994** [comment]
你使用的什么终端？git bash？

试试 powershell ？

**Comment by y0299** [comment]
git bash，Xshell，Cmder ，powerShell都用过，都是一样的错误。
docker_practice_1 | FileNotFoundError: No "README" file (or is ignored)
dockerpractice_docker_practice_1 exited with code 0

**Comment by khs1994** [comment]
是不是仓库没内容，执行 `ls` 看一下文件列表。

不行的话我在 Windows 再测试一下。

**Comment by khs1994** [comment]
报错内容来看找不到 README.md 文件。

**Comment by y0299** [comment]
我是刚从仓库中下载的代码，下载和pull都没有什么问题，是不是docker-compose up 涉及的脚本有什么新的改动 
D:\docker_practice (master)
λ ls -l
total 82
-rw-r--r-- 1 anson 197121 3380 Nov 28 09:22 README.md
-rw-r--r-- 1 anson 197121 6969 Nov 28 09:22 SUMMARY.md
-rw-r--r-- 1 anson 197121   25 Nov 28 09:22 _config.yml
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 _images/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 _layouts/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 _local/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 advanced_network/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 appendix/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 appendix_command/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 basic_concept/
-rw-r--r-- 1 anson 197121  769 Nov 28 09:22 book.json
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 cases/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 cloud/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 compose/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 container/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 coreos/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 data_management/
-rw-r--r-- 1 anson 197121  205 Nov 28 09:22 docker-compose.yml
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 etcd/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 image/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 install/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 introduction/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 kubernetes/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 machine/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 mesos/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 network/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 repository/
-rw-r--r-- 1 anson 197121 2346 Nov 28 09:22 revision.md
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 security/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 swarm/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 swarm_mode/
drwxr-xr-x 1 anson 197121    0 Nov 28 09:22 underly/

**Comment by khs1994** [comment]
在 Docker 设置里你是不是没有打开磁盘共享。

**Comment by khs1994** [comment]
`$ docker run -it --rm -v C:\Users\90621\docker_practice:/srv/gitbook-src yeasy/docker_practice`

注意替换 `C:\Users\90621\docker_practice` 为你仓库路径。

**Comment by y0299** [comment]
嗯。多谢，刚才的那个READEME找不到的问题解决了，但是又出现下面这个问题!
D:\docker_practice (master)
λ docker-compose.exe up
Starting dockerpractice_docker_practice_1 ...
Starting dockerpractice_docker_practice_1 ... done
Attaching to dockerpractice_docker_practice_1
docker_practice_1  | Live reload server started on port: 35729
docker_practice_1  | Press CTRL+C to quit ...
docker_practice_1  |
docker_practice_1  | info: 10 plugins are installed
docker_practice_1  | info: loading plugin "image-captions"... OK
docker_practice_1  | info: loading plugin "github-buttons"... OK
docker_practice_1  | info: loading plugin "page-treeview"... OK
docker_practice_1  | info: loading plugin "livereload"... OK
docker_practice_1  | info: loading plugin "highlight"... OK
docker_practice_1  | info: loading plugin "search"... OK
docker_practice_1  | info: loading plugin "lunr"... OK
docker_practice_1  | info: loading plugin "sharing"... OK
docker_practice_1  | info: loading plugin "fontsettings"... OK
docker_practice_1  | info: loading plugin "theme-default"... OK
docker_practice_1  | info: found 146 pages
docker_practice_1  | info: found 108 asset files
**docker_practice_1  | error: error while generating page "underly/network.md":
docker_practice_1  |
docker_practice_1  | Template render error: (/srv/gitbook/underly/network.md) [Line 45, Column 22]**
docker_practice_1  |   unexpected token: .
dockerpractice_docker_practice_1 exited with code 0

**Comment by khs1994** [comment]
我这里在 windows 测试了一下，出现的错误太多。

**Comment by khs1994** [comment]
等我这里测试好了再告诉你。

**Comment by khs1994** [comment]
经过测试发现文本内容出现 `大括号` 的地方都会 Windows 编译出错。

我建议 Windows 用户克隆静态文件来使用阅读。

**Comment by yeasy** [comment]
How about we remove the support of win10?

Very few developers use docker in windows.

**Comment by khs1994** [comment]
Windows 用户直接克隆静态文件(HTML)分支 `pages` `legacy-pages`

https://github.com/yeasy/docker_practice/wiki/%E7%A6%BB%E7%BA%BF%E9%98%85%E8%AF%BB%E5%8A%9F%E8%83%BD%E8%AF%A6%E8%A7%A3-Windows-10

**Comment by khs1994** [comment]
@yeasy 

增加 `travis` 编译 Gitbook 静态文件并推动到静态文件分支，需要您仓库的 `github token`，在

https://travis-ci.org 加密 `github token` 变量。

**Comment by yeasy** [comment]
@khs1994 is this good enough? https://travis-ci.org/yeasy/docker_practice

**Comment by khs1994** [comment]
稍等我编写 `.travis.yml`。

您晚上的时候设置一下 `github token`。

**Comment by khs1994** [comment]
我才发现我也有设置权限，那就不用麻烦您了。

**Comment by khs1994** [comment]
@y0299 

请按照新的 [Wiki](https://github.com/yeasy/docker_practice/wiki/%E7%A6%BB%E7%BA%BF%E9%98%85%E8%AF%BB%E5%8A%9F%E8%83%BD%E8%AF%A6%E8%A7%A3-Windows-10) 在windows 下使用离线阅读

原理:

`travis` (CI/CD) 将 gitbook 生成的静态文件（HTML）推送到指定分支

用户克隆此分支

使用 Docker Compose 启动一个 web 服务器（Nginx）挂载文件实现访问。

**Comment by khs1994** [comment]
@y0299 如果你想查看源文件（*.md） 请在其他目录克隆 `master` 分支

**Comment by y0299** [comment]
@khs1994 多谢支持。我windows已本地启动成功。
但是不能通过127.0.0.1:4000访问。我改变了访问方式为localhost:4000访问成功。

**Comment by khs1994** [comment]
欢迎给项目提建议，`127.0.0.1:4000` 我再测试一下。
