### ISSUE TITLE
Docker Desktop enable k8s

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#262]

**Comment by khs1994** [comment]
关于我增加的一些标签的说明

`new function` 仅仅指 Docker 的新增功能，其他的严禁使用该标签。

`copywriting` 是指排版存在的问题。

`deprecated` 指 Docker 废弃功能，旧的使用方法。

`spelling error` 指拼写错误。

`gitbook` 是指本项目可能会增加的功能，比如我加的离线阅读、或者 gitbook 增加一些插件。 

`new content` 指本项目增加的内容。

@yeasy 您可以指出标签的不足

**Comment by yeasy** [comment]
Looks too complicated.
Would u like to create a wiki page on the labels? 
Let’s discuss there to draft a guideline.
Btw, we either give labels based on functionality or content, rather than mixing them.

**Comment by khs1994** [comment]
https://docs.docker.com/docker-for-mac/kubernetes/

**Comment by khs1994** [comment]
https://docs.docker.com/docker-for-windows/kubernetes/
