### ISSUE TITLE
“docker 1.13+ 推荐使用docker image管理镜像” 在多页出现，感觉是重复了

### ISSUE THREAD

**Issue by burndown** [yeasy/docker_practice#263]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] CoreOS
   * [ ] Debian 8
   * [ ] Debian 9
* [ ] macOS
* [ ] Windows 10
* [ ] Others (Pls describe below)

### Docker Version

* [x] 17.11 Edge
* [ ] 17.09 Stable
* [ ] 1.13.0
* [ ] Before 1.13.0

### Problem Description

多个页面都有一下信息，我感觉是内容重复了

_Docker 1.13+

在 Docker 1.13+ 版本中推荐使用 docker image 来管理镜像。

$ docker image rm_

**Comment by khs1994** [comment]
为了让大家知道新的管理命令，多出现几次加深印象

**Comment by khs1994** [comment]
感谢您的建议
