### ISSUE TITLE
标记 中级、高级内容，提示初学者可以暂时跳过这些内容。

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#265]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] CoreOS
   * [ ] Debian 8
   * [ ] Debian 9
* [ ] macOS
* [ ] Windows 10
* [ ] Others (Pls describe below)

### Docker Version

* [x] 17.11 Edge
* [ ] 17.09 Stable
* [ ] 1.13.0
* [ ] Before 1.13.0

**Comment by yeasy** [comment]
Good idea, and we need find some better way to mark.
Maybe can add some description in the introduction first.
