### ISSUE TITLE
本项目 极客学院 wiki 同步问题！内容很久没有同步，内容太旧。

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#276]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] CoreOS
   * [ ] Debian 8
   * [ ] Debian 9
* [ ] macOS
* [ ] Windows 10
* [ ] Others (Pls describe below)

### Docker Version

* [x] 17.11 Edge
* [ ] 17.09 Stable
* [ ] 1.13.0
* [ ] Before 1.13.0

**Comment by khs1994** [comment]
http://wiki.jikexueyuan.com/project/docker-technology-and-combat/

http://wiki.jikexueyuan.com/project/help/setup-repo.html

**Comment by yeasy** [comment]
Do we have the links in the repo content?

**Comment by khs1994** [comment]
英文不好，您意思是，本项目有没有链接指向极客学院？

本项目内容，没有指向极客学院的链接。

极客学院有本项目的内容。

**Comment by khs1994** [comment]
如果不是您以前配置过，那就暂时搁置它。我目前专注于本项目内容的修订。
