### ISSUE TITLE
Change TOC

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#278]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] CoreOS
   * [ ] Debian 8
   * [ ] Debian 9
* [ ] macOS
* [ ] Windows 10
* [ ] Others (Pls describe below)

### Docker Version

* [x] 17.11 Edge
* [ ] 17.09 Stable
* [ ] 1.13.0
* [ ] Before 1.13.0

### Problem Description

将 `安全` `底层实现` 移到 `swarm mode` 之后

**Comment by khs1994** [comment]
将  DNS 从 `高级网络配置` 移到 `使用网络`

高级网络配置定位为高级应用，而修改 DNS 比较简单，初学者也可能用到。

**Comment by yeasy** [comment]
OK, and may open a new issue to track the change.
