### ISSUE TITLE
翻译官方 Dockerfile 最佳实践，并附到本书内容中

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#285]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] CoreOS
   * [ ] Debian 8
   * [ ] Debian 9
* [ ] macOS
* [ ] Windows 10
* [ ] Raspberry Pi (ARM)
* [ ] Others (Pls describe below)

### Docker Version

* [x] 17.11 Edge
* [ ] 17.09 Stable
* [ ] 1.13.0
* [ ] Before 1.13.0

### Problem Description

https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

**Comment by yeasy** [comment]
Great, and can add as an appendix item.
