### ISSUE TITLE
简化示例代码，让没有相关语言编程基础的开发人员也能看懂

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#288]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] Debian 9
   * [ ] Debian 8
   * [ ] CoreOS
* [ ] MacOS
* [ ] Windows 10
* [ ] Raspberry Pi (ARM)
* [ ] Others (Pls describe below)

### Docker Version

* [x] 17.11 Edge
* [ ] 17.09 Stable
* [ ] 1.13.0 or Before

### Problem Description

例如 java 开发人员可能不懂 python，那么用 python 举的例子，其他语言的开发者看起来就会很困惑。

https://github.com/yeasy/docker_practice/blob/master/compose/usage.md

**Comment by khs1994** [comment]
除了 `docker-compose` 代码，避免大段代码出现在正文内容中。

**Comment by yeasy** [comment]
Agree, maybe can just give core sample code, while necessary full code as files.
