### ISSUE TITLE
多多介绍可以通过 Docker 容器部署的工具，例如 Gogs

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#289]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [ ] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] Debian 9
   * [ ] Debian 8
   * [ ] CoreOS
* [ ] MacOS
* [ ] Windows 10
* [ ] Raspberry Pi (ARM)
* [ ] Others (Pls describe below)

### Docker Version

* [x] 17.11 Edge
* [ ] 17.09 Stable
* [ ] 1.13.0 or Before

**Comment by yeasy** [comment]
this one? https://gogs.io/
