### ISSUE TITLE
修正PID的获取代码

### ISSUE THREAD

**Issue by charlieyu** [yeasy/docker_practice#293]
那个.bashrc_docker 里面获取pid的代码有误，在新版的docker ce里获取不到pid
原来是 PID=$(sudo docker inspect --format “” "$1")
正确的是 PID=$(sudo docker inspect --format {{.State.Pid}} "$1")

**Comment by khs1994** [comment]
这段不是已经删除了吗

**Comment by khs1994** [comment]
既然你使用的 Docker CE 就查看 `mastet` 分支，`.bashrc_docker` 这部分内容早就删除了，是你查看的内容太旧还是怎么回事。

**Comment by charlieyu** [comment]
抱歉，发issue的时候没再去确认这段代码。我11月20日的时候，还推荐过我同事使用，那时候还在。这脚本我已经用了一年多了。你们不再维护，是不是这脚本还有其他问题。

**Comment by khs1994** [comment]
https://github.com/yeasy/docker_practice/blob/docker-legacy/_local/.bashrc_docker

这段脚本没有找到你说的问题，或者你提交一下 PR。

自定义脚本暂时移除了，现在专注 docker 原始命令。

**Comment by khs1994** [comment]
这段脚本之前是为了进入容器，现在有了新命令 `docker exec`，就删除了。

你们使用这个脚本干什么，为了获取 pid ?

可以说一下使用场景吗？

**Comment by khs1994** [comment]
会用 github 的话，尽量提交 PR 吧。

**Comment by khs1994** [comment]
我看了你的博文

https://github.com/charlieyu/charlieyu.github.io/blob/master/_posts/blog/2017-11-20-docker%20%E5%AE%89%E8%A3%85%E5%8F%8A%E5%B8%B8%E7%94%A8%E8%84%9A%E6%9C%AC.md

进入容器请使用 `docker exec` `docker-compose exec`
