### ISSUE TITLE
electronic book download problem

### ISSUE THREAD

**Issue by doudoubean** [yeasy/docker_practice#307]
The PDF electronic book can not download from this URL that you gived 。
https://www.gitbook.com/download/pdf/book/yeasy/docker_practice
If you can do, I expect you can offer a url from dropbox or Baidu Netdisk。
Please quickly fix it, thanks!

**Comment by khs1994** [comment]
网络问题

**Comment by khs1994** [comment]
暂不接受第三方链接，感谢。

**Comment by khs1994** [comment]
后续会把 pdf 附到 releases 页面，并同步到国内 git 镜像

**Comment by khs1994** [comment]
请到 releases 页面下载 https://github.com/yeasy/docker_practice/releases

或在国内镜像下载 https://gitee.com/docker_practice/docker_practice/releases
