### ISSUE TITLE
關於繁體版出實體書

### ISSUE THREAD

**Issue by philipz** [yeasy/docker_practice#31]
yeasy 您好：
因 Docker.Taipei 社群受惠於您的開放著作，並以社群力量翻譯成繁體版。日前基峰出版社與 Docker.Taipei 接洽，希望能印製實體書籍，礙於之前授權只同意 gitbook 網上閱讀，須經您同意才可後續出版事宜，繁體版也會增加台灣系統案例等章節，所有繁體版稅將全數用於 Docker 技術推廣和社群使用。還請 yeasy 您告知，無論同意與否，再次感謝您的貢獻和無私分享，非常謝謝您！

**Comment by m31271n** [comment]
Docker 的进展速度飞快， 互联网上的相关内容都难以及时更新。即使出了这本书，过不了多久，内容也会很快过时。

对 基峰出版社 说几句：
在社区产生的东西，就让它永远单纯地存在于社区里，好吗？
不要因为一个出版社的几句蛊惑，就开始向社区伸手，好吗？
不要总是利用 “放在书架上的书就是我们脑里的知识” 来让我们买书，好吗？
“所有版税用于 Docker 技术推广 和 社群使用”， 哪个社群，哪里的 Docker 技术推广？

''yeasy 我希望你们不要同意。''

**Comment by yeasy** [comment]
Hi, philipz, thanks for your comment!

First, I would prefer keeping this online book open sourced. The content is contributed by  our dockerpool community and other Docker fans, and part of the content references the official documentation.
On the other hand, we have made another book (focusing on practical cases and technical details) published already, hope it can help people (like you maybe) who prefer reading paper books.

How do you think? Please feel free send me comments.
Thanks a lot!

**Comment by yeasy** [comment]
Hi, m31271n.
Do not worry. :)
I also love open source communities. 
Hope my decision (in previous reply) is OK for you.

**Comment by m31271n** [comment]
;)

**Comment by philipz** [comment]
Dear yeasy,
Thank for your correct answer. Docker tech. improve day by day, the online book is best choice.
I will reject the publisher.
