### ISSUE TITLE
配置全局容器的 DNS 未生效

### ISSUE THREAD

**Issue by qiujichun** [yeasy/docker_practice#310]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

**CentOS 7**

### Docker Version

**V1.12.6**

### Problem Description

我在daemon.json中配置了DNS

```bash
# cat /etc/docker/daemon.json 
{
  "registry-mirrors": ["https://docker.mirrors.ustc.edu.cn"]
}
{
  "dns" : ["114.114.114.114","8.8.8.8"]
}

```

但是运行的容器nameserver并未随之生效

```bash
# docker run --rm -it custom/rhel73 cat /etc/resolv.conf
### # Generated by NetworkManager


# No nameservers found; try putting DNS servers into your
# ifcfg files in /etc/sysconfig/network-scripts like so:
#
# DNS1=xxx.xxx.xxx.xxx
# DNS2=xxx.xxx.xxx.xxx
# DOMAIN=lab.foo.com bar.foo.com
nameserver 10.10.71.254
```

**Comment by khs1994** [comment]
`daemon.json` 也许不支持 `Docker 1.12.6`

没有低版本 Docker 供我测试，给不了你解决办法。

有特殊要求必须使用该版本的 Docker 吗？如果没有要求，请参照 `安装一节` 尽快升级到 `v18.01`

**Comment by khs1994** [comment]
再说，你那个 `daemon.json` 的格式也不对啊。你格式不对，docker 还能正常启动？那就说明 1.12.6 不支持 `daemon.json`

**Comment by khs1994** [comment]
还有，我记得 Docker 默认挂载宿主机的 `/etc/resolv.conf` 文件作为 DNS 配置，你试试在宿主机配置一下，看行不行

**Comment by qiujichun** [comment]
1、我试过"挂载宿主机的 /etc/resolv.conf 文件作为 DNS 配置" 可以生效

2、现在正在尝试升级docker，顺便请教下docker-engine和docker-ce安装哪个？

谢谢！

**Comment by khs1994** [comment]
自行查看 安装一节

**Comment by qiujichun** [comment]
好的，多谢！
