### ISSUE TITLE
docker-compose cannot start in windows 

### ISSUE THREAD

**Issue by y0299** [yeasy/docker_practice#311]
### Environment
* [x] Windows 10

### Docker Version
* [x] Stable (17.09.0-ce-win33 )

### Problem Description

```bash
$ git fetch --depth=1 origin pages
remote: Counting objects: 266, done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 266 (delta 176), reused 251 (delta 162), pack-reused 0
Receiving objects: 100% (266/266), 813.31 KiB | 89.00 KiB/s, done.
Resolving deltas: 100% (176/176), completed with 22 local objects.
From https://github.com/yeasy/docker_practice
 * branch            pages      -> FETCH_HEAD
 + cacd1fb...300ac74 pages      -> origin/pages  (forced update)

anson@y0299A MINGW64 /d/Learning_GitHub/docker_practice_windows/docker_practice (pages)
$ git branch -a
* pages
  remotes/origin/pages

anson@y0299A MINGW64 /d/Learning_GitHub/docker_practice_windows/docker_practice (pages)
$ git reset --hard origin/pages
HEAD is now at 300ac74 Travis CI Site updated 2018-01-16 16:33:26

$ docker-compose up windows
Recreating dockerpractice_windows_1 ...
Recreating dockerpractice_windows_1 ... done
Attaching to dockerpractice_windows_1
windows_1      | 2018/01/23 11:17:40 [emerg] 1#1: open() "/etc/nginx/conf.d/nginx.conf" failed (2: No such file or directory)
windows_1      | nginx: [emerg] open() "/etc/nginx/conf.d/nginx.conf" failed (2: No such file or directory)
```

**Comment by khs1994** [comment]
在 Powershell 中试试

**Comment by y0299** [comment]
在 Powershell 中是一样的
PS D:\Learning_GitHub\docker_practice_windows\docker_practice> docker-compose.exe up windows
Starting dockerpractice_windows_1 ...
Starting dockerpractice_windows_1 ... done
Attaching to dockerpractice_windows_1
windows_1      | 2018/01/23 11:37:24 [emerg] 1#1: open() "/etc/nginx/conf.d/nginx.conf" failed (2: No such file or directory)
windows_1      | nginx: [emerg] open() "/etc/nginx/conf.d/nginx.conf" failed (2: No such file or directory)
dockerpractice_windows_1 exited with code 1
PS D:\Learning_GitHub\docker_practice_windows\docker_practice>

**Comment by khs1994** [comment]
`docker` 设置里磁盘共享打开了吗？

**Comment by y0299** [comment]
打开了。
之前的一个版本，windows上是好使的，能够启动，git pull下载新的代码后，启动失败！
你可以试试

**Comment by khs1994** [comment]
你先到 https://docker_practice.gitee.io/ 这里阅读吧，我先调试一下。

**Comment by khs1994** [comment]
刚试了，没问题。把项目删了，重新按照步骤再试试。

**Comment by khs1994** [comment]
我实在是不知道你那里怎么就挂载不上文件，我现在正在重新设计一下离线阅读，尽量一条命令就能启动。

**Comment by y0299** [comment]
嗯，多谢，能用一条命令启动的话，会方便很多

**Comment by khs1994** [comment]
请查看 [wiki](https://github.com/yeasy/docker_practice/wiki/%E7%A6%BB%E7%BA%BF%E9%98%85%E8%AF%BB%E5%8A%9F%E8%83%BD%E8%AF%A6%E8%A7%A3)
