### ISSUE TITLE
删除多余字符

### ISSUE THREAD

**Issue by Drshu** [yeasy/docker_practice#314]
* [x] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7

### Docker Version

* [x] Stable (v17.12)

### Problem Description

书中第62页（PDF Version），介绍*Untagged和Deleted*之中` docker rm`后面出现了多余的`i`

**Comment by khs1994** [comment]
正确，请仔细阅读。
