### ISSUE TITLE
[警告] 计划 2018 年 5 月 1 日 移除 docker-legacy 分支 || Remove docker-legacy branch 2018.05.01

### ISSUE THREAD

**Issue by khs1994** [yeasy/docker_practice#328]
之后旧版本（1.13-）内容请到

* https://github.com/yeasy/docker_practice/tree/cd660f8f9352c6c01e6707ba4f5f069414c53685

阅读

**Comment by khs1994** [comment]
* GitBook(HTML 文件)

* https://github.com/yeasy/docker_practice/releases/download/v0.9.0/docker_practice_legacy_pages.zip

**Comment by yeasy** [comment]
还有不少人在看旧版本，legacy可以保留时间再长一些，到年底吧。
