### ISSUE TITLE
docker_sven

### ISSUE THREAD

**Issue by whenyougone** [yeasy/docker_practice#331]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [ ] Linux
   * [ ] CentOS 7
   * [x] Ubuntu 16.04
   * [ ] Ubuntu 17.10
   * [ ] Debian 9
   * [ ] Debian 8
   * [ ] CoreOS
* [x] Windows 10
* [ ] Raspberry Pi (ARM)
* [ ] Others (Pls describe below)
* [ ] macOS

### Docker Version

* [x] Edge (v18.04)
* [x] Stable (v18.03)
* [x] 1.13.0 or Before

**Comment by whenyougone** [comment]
docker

**Comment by yeasy** [comment]
Since no question description, need to close this issue.
