### ISSUE TITLE
docker install not support CentOS6.5?

### ISSUE THREAD

**Issue by zhizhi555555** [yeasy/docker_practice#333]
Hi 
  I  just study the docker,but have an issued need to help.
  the environment  
  CentOS 6.5 
  and when input the command 
  ```
   sudo yum makecache fast
   ```
    there have error response as below.
     Loading mirror speeds from cached hostfile
 * base: mirrors.cn99.com
 * extras: mirrors.cn99.com
 * updates: mirrors.cn99.com

base                                                                               | 3.7 kB     00:00     
https://download-stage.docker.com/linux/centos/7/x86_64/edge/repodata/repomd.xml: [Errno 14] problem making ssl connection
Trying other mirror.
**Error: Cannot retrieve repository metadata (repomd.xml) for repository: docker-ce-edge. Please verify its path and try again**

so i think is that the issue because of the CentOS version ?
can anyone help me? thanks very much.

**Comment by khs1994** [comment]
7.0 兼容性都不怎么样，何况 6.x?

**Comment by khs1994** [comment]
仔细按照安装一节，选择合适的操作系统！
