### ISSUE TITLE
是否存在术语表达错误？

### ISSUE THREAD

**Issue by Deeer** [yeasy/docker_practice#336]
https://yeasy.gitbooks.io/docker_practice/content/image/rm.html#
在该章节的 Untagged 和 Deleted小节中，是否存在术语表达错误？

>因为一个镜像可以对应多个标签，因此当我们删除了所指定的标签后，可能还有别的标签指向了这个镜像，如果是这种情况，那么 Delete 行为就不会发生。所以并非所有的 docker rmi 都会产生删除镜像的行为，有可能仅仅是取消了某个标签而已。

其中 , `所有的 docker rmi` 应更改为`所有的docker untagged`

**Comment by khs1994** [comment]
`docker rmi` 这里指的是 `docker rmi` 这个命令，我已经改为了 `docker image rm`
