### ISSUE TITLE
docker run hello-world permission denied.

### ISSUE THREAD

**Issue by g10guang** [yeasy/docker_practice#340]
* [x] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] Ubuntu 16.04

### Docker Version

* [x] Stable (v18.03)
* [x] Stable (v18.05)

### Problem Description

直接执行：

```
docker run hello-world
```

错误，提示没有权限链接 unix socket，即使执行了：

```
usermod -aG docker $USER
```

我去 docker 的 issue 看了：[https://github.com/docker/compose/issues/1214](https://github.com/docker/compose/issues/1214)

得到的解决方案是：

```
sudo docker run hello-world
```

需要加上 sudo 权限。

**Comment by khs1994** [comment]
退出当前终端，再试试。

**Comment by l501727751** [comment]
`sudo chmod a+rw /var/run/docker.sock` 试试！

> * [x]  Have u googled the problem? If no, pls do that first!
> 
> ### Environment
> * [x]  Linux
>   
>   * [x]  Ubuntu 16.04
> 
> ### Docker Version
> * [x]  Stable (v18.03)
> * [x]  Stable (v18.05)
> 
> ### Problem Description
> 直接执行：
> 
> ```
> docker run hello-world
> ```
> 错误，提示没有权限链接 unix socket，即使执行了：
> 
> ```
> usermod -aG docker $USER
> ```
> 我去 docker 的 issue 看了：[docker/compose#1214](https://github.com/docker/compose/issues/1214)
> 
> 得到的解决方案是：
> 
> ```
> sudo docker run hello-world
> ```
> 需要加上 sudo 权限。

sudo chmod a+rw /var/run/docker.sock
