### ISSUE TITLE
ubuntu16.04 中 bash路径为 /bin/bash

### ISSUE THREAD

**Issue by ShaofeiZi** [yeasy/docker_practice#342]
* [x] Have u googled the problem? If no, pls do that first!

### Environment
 #

* [x] Linux
   * [x] CentOS 7
   * [x] Ubuntu 16.04
   * [x] Ubuntu 17.10
   * [x] Debian 9
   * [x] Debian 8
   * [x] CoreOS
* [x] macOS
* [x] Windows 10
* [x] Raspberry Pi (ARM)
* [x] Others (Pls describe below)

### Docker Version

* [] Edge (v18.04)
* [x] Stable (v18.03)
* [] 1.13.0 or Before

### Problem Description

 ubuntu:16.04 中 bash路径为 /bin/bash 而不是/bash
`docker run -it ubuntu:16.04 /bash
`
`
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bash\": stat /bash: no such file or directory": unknown
`

`
 docker run -it ubuntu:16.04 /bin/bash
`
`
root@fe2a8f073147:/#
`

**Comment by khs1994** [comment]
请指出这部分内容的位置。

**Comment by khs1994** [comment]
没有 Linux 使用经验吗？你多加了`/`

**Comment by ShaofeiZi** [comment]
不好意，书中有个\  然后我在window中，脑补过了 把‘\’ 自动转成‘/’ 了
