### ISSUE TITLE
docker 镜像与虚拟机疑问

### ISSUE THREAD

**Issue by Macx10086** [yeasy/docker_practice#348]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7

### Docker Version

* [x] Stable (v18.03)

### Problem Description

有个问题，教程里面提到docker直接运行于宿主内核，但是我现在接触到的docker基本都要基于虚拟机的镜像进行制作，这样的docker做到的应该也是基于虚拟机，只不过这个虚拟机镜像会将所需要执行的命令反馈给下面的虚拟机，只不过所损耗的资源比直接虚拟出一台新的虚拟机少，可以这样理解吗

**Comment by yeasy** [comment]
镜像是镜像，实际上运行时是直接使用宿主机的内核功能（MacOS和Win环境下除外）。
实际上，最早 Docker 的实现是借用的Linux 下的 LXC 功能，可以看一下。

**Comment by Macx10086** [comment]
额。如果是直接使用宿主机的内核功能，那为什么大部分镜像仍然需要依赖于centos，redhat等进行制作，如果宿主机是windows，镜像依赖于centos进行制作，那这个容器运行时与利用vm虚拟出来的centos有何区别？效率如何？

**Comment by yeasy** [comment]
其实不是必须依赖centos、redhat等镜像制作。这是历史原因。
最早拿这些os的镜像做基础镜像多，后期很多镜像都不依赖它们了，例如golang。

宿主机是win/macos情况下，目前仍然会依赖虚拟机技术，但会有一些优化。

如果注重效率，最好还是在linux系统上用。
