### ISSUE TITLE
删除镜像应该用是rmi命令吧？

### ISSUE THREAD

**Issue by tinydull** [yeasy/docker_practice#355]
删除镜像应该用是rmi命令吧？书中写的是不是错误了？

**Comment by khs1994** [comment]
`image rm` = `rmi`
`container ls` = `ps`

为了方便区分各对象（容器、镜像、数据卷），建议使用 `container` `image` `volume` 子命令代替原来的，另官方文档也在使用  `image rm` 等子命令。

**Comment by khs1994** [comment]
#279
