### ISSUE TITLE
Docker三剑客之一compose - 实战wordpress 示例代码运行错误！！！

### ISSUE THREAD

**Issue by shangdev** [yeasy/docker_practice#356]
### Environment
macOS

### Docker Version
Stable (v18.06)

### Problem Description
![image](https://user-images.githubusercontent.com/15621520/44619090-ad9a8f00-a8b3-11e8-917f-d3a5a7ddcc0f.png)
执行示例代码时出错！！！

**Comment by khs1994** [comment]
`volumes` 从行开头开始，没有空格。
