### ISSUE TITLE
english translation

### ISSUE THREAD

**Issue by DanielRuf** [yeasy/docker_practice#363]
Would be great to have an english translation.

**Comment by yeasy** [comment]
yes, and if you wanna volunteer, will be glad to create a branch for that.

**Comment by DanielRuf** [comment]
Not sure how I should translate the content. We need a native speaker who understand both languages in general.

**Comment by tranduykhanh** [comment]
Any volunteers here? I don't know chinese 😢

**Comment by ouyangjunfei** [comment]
- English Version is available in Docker documentation [site](https://docs.docker.com/).
- It writes well and is easy to read and understand.
- To get latest info about docker, official doc is necessary.
^_^

**Comment by yeasy** [comment]
Besides, google can automatically translate website or content.

**Comment by DanielRuf** [comment]
> Besides, google can automatically translate website or content.

This is generally not possible or available in many cases (working offline) and not the best option for all users and does not help others to work with this project or contribute with correct grammar (would I have to write in another language?). ;-)

**Comment by yeasy** [comment]
OK, let me reopen this for a while, and see if we are lucky to find some volunteers.

**Comment by 00Kai0** [comment]
I am poor in English, but I want to help just for learning Docker and English^_^

**Comment by xrfinbupt** [comment]
> yes, and if you wanna volunteer, will be glad to create a branch for that.

不管怎么样，建议 先用google翻译一版本，做到从0到1，后续在考虑怎么优化体验

**Comment by yeasy** [comment]
Anyone wanna start the work, feel free to let me know, i will create a corresponding branch like en_US, just as the zh_Hant branch.

**Comment by 00Kai0** [comment]
@yeasy I am in.

**Comment by yeasy** [comment]
@00Kai0 OK, so i will create a new branch **english** based on latest master for you to start?

**Comment by 00Kai0** [comment]
@yeasy OK, I will try my best.

**Comment by yeasy** [comment]
Here it is: https://github.com/yeasy/docker_practice/tree/english

**Comment by junchen1992** [comment]
@yeasy Do we still need volunteers to do the Chinese to English translation? I'm interested in this work :)

**Comment by yeasy** [comment]
@junchen1992 sure, feel free to join.
You can commit the translated result to the `english` branch.

https://github.com/yeasy/docker_practice/tree/english.

**Comment by Bill0412** [comment]
I have fixed the typos in the translated chapters, and from today on, I will try to translate the rest.
