### ISSUE TITLE
add-apt-repository not good idea on raspberry

### ISSUE THREAD

**Issue by xiaoyao9184** [yeasy/docker_practice#369]
* [x] googled!

### Environment

* [x] Raspberry Pi 3B+(ARM stretch)

### Docker Version

* [x] Stable (v18.09)

### Problem Description

Cant use this command in [使用-apt-安装](https://github.com/yeasy/docker_practice/blob/master/install/raspberry-pi.md#%E4%BD%BF%E7%94%A8-apt-%E5%AE%89%E8%A3%85)

```bash
$ sudo add-apt-repository \
    "deb [arch=armhf] https://mirrors.ustc.edu.cn/docker-ce/linux/raspbian \
    $(lsb_release -cs) \
    stable"
```
add-apt-repository: command not found

for use this you must install software-properties-common

> sudo apt-get update
sudo apt-get install software-properties-common

or use written in the [official document](https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository)

```bash
$ echo "deb [arch=armhf] https://download.docker.com/linux/debian \
     $(lsb_release -cs) stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list
```

**Comment by khs1994** [comment]
安装准备一节已说明
