### ISSUE TITLE
docker-cn 的镜像更新是不是有延迟，建议更换

### ISSUE THREAD

**Issue by strongwong** [yeasy/docker_practice#370]
### Environment

* [x] Linux
   * [x] Ubuntu 16.04 +

### Docker Version

* [x] Stable (v18.06)

### Problem Description

我的 gitlab 提醒我更新有一个星期了，于是我就准备重新 pull 一下，重建容器，但是，我发现我更新之后，gitlab 还是旧版本，依然提醒我更新。于是我换到了阿里的镜像加速，就可以正常更新了！

**Comment by yeasy** [comment]
Maybe open an ticket for docker-cn first.

**Comment by khs1994** [comment]
latest 标签的镜像可能不及时，我也有此感觉，你可以尝试其他镜像，方法里面已经列出。

**Comment by khs1994** [comment]
https://registry.docker-cn.com 暂时不可用，请 **立即** 更换其他镜像。

**Comment by khs1994** [comment]
https://dockerhub.azk8s.cn 目前仅供 Azure 内部访问，请 **立即** 更换其他镜像。
