### ISSUE TITLE
The delete mirror section is missing a case description

### ISSUE THREAD

**Issue by gangyahaidao** [yeasy/docker_practice#393]
here is the 'docker image ls' ouput:
![image](https://user-images.githubusercontent.com/25075558/55269767-1460aa80-52d2-11e9-94c3-6739dee1106c.png)

we can see than this image's tag is \<none\>, such image we can delete it by it's id:
`docker image rm ed026219cb8c`

This is not covered in the documentation

**Comment by khs1994** [comment]
https://github.com/yeasy/docker_practice/blob/master/image/rm.md#%E7%94%A8-id%E9%95%9C%E5%83%8F%E5%90%8D%E6%91%98%E8%A6%81%E5%88%A0%E9%99%A4%E9%95%9C%E5%83%8F
