### ISSUE TITLE
网络和端口怎么规划？

### ISSUE THREAD

**Issue by double-scars** [yeasy/docker_practice#397]
我尝试在一个centos7中安装了docker，然后尝试安装不同容器，其中的问题是端口冲突和网络规划问题；其一我先说关于端口的疑问，比如我我部署了一个网站应用，它所用的端口是80，映射到宿主机上也是80，然后我再部署一个网站应用，它所用的端口是8080，映射到宿主机上的端口也是8080，当我部署第三个网站的时候，网站的默认的端口是80或者8080，我映射到我指定的宿主机端口后，是无法能被访问的，这边我想到在docker中部署很多网站的话，这个端口该如何去规划呢？新建容器的时候的语法要怎么自定义呢？其二是网络问题，最根本的是IP问题，容器默认使用的都是docker0这个虚拟网卡所分配的地址，我网站的话可以通过端口映射使用宿主机的IP去访问，而我若是安装了kali，oracle，aix等主机容器，我想在内网内直接通过ssh远程容器，但是容器是拒绝连接的，无论我是用宿主机的ip+端口远程还是直接远程容器的ip，现在我感觉好混乱，跪求大神点醒一波思路，指点指点。

**Comment by yeasy** [comment]
Basically, docker maps container ports to host via iptables.
Hence you can point a container port to arbitrary unused host port.

**Comment by double-scars** [comment]
> Basically, docker maps container ports to host via iptables.
> Hence you can point a container port to arbitrary unused host port.

thank you very much
