### ISSUE TITLE
新建立的docker网络不能通过容器名字来ping,只能通过ip来ping

### ISSUE THREAD

**Issue by MackYang** [yeasy/docker_practice#403]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
    
   * [x] Ubuntu 18.04 +
    

### Docker Version

 
* [x] Stable (v18.09.6)
 

### Problem Description

docker network create -d bridge my-net

docker run -it --rm --name busybox1 --network my-net busybox sh
docker run -it --rm --name busybox2 --network my-net busybox sh

在busybox2的终端中ping busybox1
ping busybox1
ping: bad address 'busybox1'

在busybox1中ping busybox2也是同样的错误

但2个容器之间ping ip是可以ping通的,请问要怎么操作才能用 容器名 ping通呢?

**Comment by khs1994** [comment]
我这里尝试是没有问题的。

busybox1 busybox2 执行

```bash
cat /etc/resolv.conf
```

看看 DNS 结果
