### ISSUE TITLE
安装docker时遇到的问题

### ISSUE THREAD

**Issue by TheStarBoys** [yeasy/docker_practice#404]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] Ubuntu 18.04 +

### Docker Version

* [x] Edge (v18.09)
* [x] Stable (v18.09)
* [x] 1.13.0 or Before

### Problem Description

安装Docker后，添加用户到docker用户组的之后，关闭终端并重新登录后，并不能以非Root用户的形式，运行docker容器。
![image](https://user-images.githubusercontent.com/41286328/59483581-ad9a6880-8ea0-11e9-8ab5-c85a6103645b.png)
使用以下命令后，才可以成功运行容器。
newgrp docker     #更新用户组
docker ps    #测试docker命令是否可以使用sudo正常使用

**Comment by khs1994** [comment]
用户注销，或重启
