### ISSUE TITLE
docker-compose使用Django报错

### ISSUE THREAD

**Issue by Sad-polar-bear** [yeasy/docker_practice#405]
qinshilin:222 qinshilin$ docker-compose run web django-admin.py startproject django_example .
Starting 222_db_1 ... done
Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"django-admin.py\": executable file not found in $PATH": unknown
报错信息如上。

报错原因：未执行build操作。docker-compose run命令启动容器，并不会根据Dockerfile构建镜像，而是根据指定的service（即这里的web）查找并运行$PROJECT_web名称的镜像并运行（这里的$PROJECT为您当前目录的目录名称，默认以该目录名称作为该compose项目的项目名）。由于未构建出该镜像，所以会报上述的django-admin.py可执行文件找不到。

解决办法：我们正确的逻辑应该是先根据Dockerfile构建出包含web基础环境的image，然后运行docker-compose run命令生成django工程项目，再按照文中的流程继续下一步骤：
`$ docker-compose build   //读取docker-compose.yml文件中的build指令并构建镜像`
`$ docker-compose run web django-admin.py startproject django_example .  //运行web（必须是docker-compose中定义）服务容器，生成django工程通过docker volume映射到宿主机，然后修改settings.py的数据库连接信息`

**Comment by khs1994** [comment]
运行 `docker-compose run` 命令时，若使用的镜像不存在，会先构建再运行。所以没必要运行 `docker-compose build`

**Comment by khs1994** [comment]
报错的原因是  `django-admin.py` 不存在，经查找，改为 `django-admin` 即可。具体更改请查看 https://github.com/yeasy/docker_practice/commit/b9247c16df88039378e1ac3fe524f7ca367a7f99
