### ISSUE TITLE
请教一下这里面 pdf 文件是如何生成的？

### ISSUE THREAD

**Issue by nibocn** [yeasy/docker_practice#410]
在本地使用 `gitbook` 命令生成 pdf 文件时发现如果有中文整个生成的 pdf 文件大小就会非常大（几十 M），想请教下这里面 pdf 文件是如何生成的？是通过 gitbook 官网直接生成的？还是有什么特别的配置处理？查看了这里面相关的配置和构建脚本没有特别相关的发现，希望能解答下，谢谢。

**Comment by khs1994** [comment]
通过 gitbook 官网直接生成，gitbook 提供 pdf 下载链接。

**Comment by snow212-cn** [comment]
> 通过 gitbook 官网直接生成，gitbook 提供 pdf 下载链接。

旧版官方网站被废弃了😭请问现在2021年如何获取pdf

**Comment by khs1994** [comment]
@snow212-cn  #455
