### ISSUE TITLE
按照您的文章进行操作的时候遇到个小问题.

### ISSUE THREAD

**Issue by whiteS18** [yeasy/docker_practice#412]
* [x] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Windows 10

### Docker Version

* [x] Stable (v18.09)

### Problem Description

你好,我本地操作系统为WIN专业版,docker安装的环境是Ubuntu18.04
按照您的文章内容进行操作学习,遇到了个小问题,
使用 Dockerfile 定制镜像一节中

在一个空白目录中，建立一个文本文件，并命名为 Dockerfile：
```
$ mkdir mynginx
$ cd mynginx
$ touch Dockerfile
```
其内容为：
```
FROM nginx
RUN echo '<h1>Hello, Docker!</h1>' > /usr/share/nginx/html/index.html
```
请问`其内容为`后面的的代码块改怎么写入Dockerfile中?我使用` vi Dockerfile`和` vim Dockerfile`
命令都提示我命令未找到,请问这个该如何解决?

**Comment by yeasy** [comment]
You're using Ubuntu 18.04, then you can install vi/vim as the following:

sudo apt-get update && sudo apt-get install vim -y
