### ISSUE TITLE
Update swarm mode chapter since docker-machine is superseded

### ISSUE THREAD

**Issue by janetat** [yeasy/docker_practice#426]
1. #425 
2. https://docs.docker.com/ee/
3. https://github.com/docker/machine/issues/4537
Docker-machine is superseded.

**Comment by janetat** [comment]
https://yeasy.gitbooks.io/docker_practice/content/swarm_mode/create.html creates node by docker-machine.

**Comment by janetat** [comment]
I am a newbie and get a little confused about how to utilize docker swarm mode without docker-machine.

**Comment by khs1994** [comment]
* https://www.mirantis.com/blog/mirantis-acquires-docker-enterprise-platform-business/

>前进的主要协调者是Kubernetes。Mirantis致力于为所有Docker Enterprise平台客户提供出色的体验，并且目前希望根据客户对路线图的投入，为Swarm提供至少两年的支持。Mirantis还正在评估使Swarm用户更容易过渡到Kubernetes的选项。

You can run other dockerd on VM.

**Comment by khs1994** [comment]
https://www.mirantis.com/blog/mirantis-will-continue-to-support-and-develop-docker-swarm/

swarm_mode 会继续得到支持
