### ISSUE TITLE
mesos-master quorum  设置错误导致 master 节点启动失败

### ISSUE THREAD

**Issue by zhangyucumt** [yeasy/docker_practice#429]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment
* [x] Linux
   * [x] CentOS 7

### Docker Version
* [x] Stable (v19.03)

### Problem Description
第26章中 mesos-master  配置 quorum   参数和 zk  节点无关  而是指的  mesos-master 节点的个数。否则 mesos-master 会一直重启
报 Recovery failed: Failed to recover registrar: Failed to perform fetch within 1mins 的错误
![image](https://user-images.githubusercontent.com/16399713/69009929-3019dd80-0995-11ea-8790-32951dd22882.png)

**Comment by khs1994** [comment]
mesos 这一块目前不进行维护（本人不了解），如果有兴趣你可以提 PR 修复。

**Comment by khs1994** [comment]
你看的实体书吧，请 @yeasy 查看。
