### ISSUE TITLE
在kindle上閱讀，字體顏色太淡

### ISSUE THREAD

**Issue by ycavatars** [yeasy/docker_practice#43]
你好，我在kindle touch上閱讀時，發現字體顏色偏淡變成淺灰色，不是純黑，閱讀起來會覺得有點吃力，請問有什麼方式能讓字體顏色正確呢？謝謝。

**Comment by yeasy** [comment]
Not familiar with kindle font setting.
Please refer to the gitbook project or the kindle producer.
Thanks!
