### ISSUE TITLE
环境变量可以在 RUN 指令内使用

### ISSUE THREAD

**Issue by islishude** [yeasy/docker_practice#430]
[书上说](https://yeasy.gitbooks.io/docker_practice/content/image/dockerfile/env.html)：

> 在这里先定义了环境变量 NODE_VERSION，其后的 RUN 这层里，多次使用 $NODE_VERSION 来进行操作定制。可以看到，将来升级镜像构建版本的时候，只需要更新 7.2.0 即可，Dockerfile 构建维护变得更轻松了。下列指令可以支持环境变量展开： ADD、COPY、ENV、EXPOSE、LABEL、USER、WORKDIR、VOLUME、STOPSIGNAL、ONBUILD。

官方[文档]也说在 RUN 指令中不能使用环境变量

> Environment variables are supported by the following list of instructions in the Dockerfile: ADD COPY ENV EXPOSE FROM LABEL STOPSIGNAL USER VOLUME WORKDIR as well as: ONBUILD (when combined with one of the supported instructions above)

这里确实没有 RUN 

但是书上的示例代码以及很多镜像都是用了环境变量，这里有个自己试验了一遍

```console
$ cat Dockerfile
FROM alpine:3.10
ENV FOO=bar
RUN echo "$FOO"
RUN echo ${FOO}
$ docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM alpine:3.10
 ---> 965ea09ff2eb
Step 2/4 : ENV FOO=bar
 ---> Running in a95d319370fb
Removing intermediate container a95d319370fb
 ---> a41d1f6dcadf
Step 3/4 : RUN echo "$FOO"
 ---> Running in 1ab211ce0ed5
bar
Removing intermediate container 1ab211ce0ed5
 ---> c62e670a1de2
Step 4/4 : RUN echo ${FOO}
 ---> Running in a820dd82e404
bar
Removing intermediate container a820dd82e404
 ---> 98aee4257234
Successfully built 98aee4257234
Successfully tagged test:latest
```

有点让人困惑

**Comment by khs1994** [comment]
肯定是可以在 `RUN` 中使用 `ENV` 中设置的值的。官方文档错了，你可以提 PR 修复官方文档。

* https://github.com/docker-library/golang/blob/f30f0428221b94c7dcb414ebdcea83106df20897/1.13/buster/Dockerfile
