### ISSUE TITLE
我在k8s

### ISSUE THREAD

**Issue by 905839698** [yeasy/docker_practice#442]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7

v18.09.6
### Problem Description

我修改daemon.json 配置文件，想修改docker0的ip地址 ，但是重启docker后还是原来docker0的ip地址，bip没有生效

**Comment by khs1994** [comment]
重建网桥试试，参考 https://www.cnblogs.com/rootid/p/9317772.html

**Comment by 905839698** [comment]
我已经按照这个教程做了 只是还没有重启主机，没有效果

发件人: Kang Huaishuai <notifications@github.com>
发送时间: 2020年3月18日 16:13
收件人: yeasy/docker_practice <docker_practice@noreply.github.com>
抄送: 905839698 <yangjianchun88@outlook.com>; Author <author@noreply.github.com>
主题: Re: [yeasy/docker_practice] 我在k8s (#442)


重建网桥试试，参考 https://www.cnblogs.com/rootid/p/9317772.html

**Comment by khs1994** [comment]
重启主机试试
