### ISSUE TITLE
离线阅读功 不能启动, 需要追加 docker-entrypoint.sh 的执行权限

### ISSUE THREAD

**Issue by bySHIFT** [yeasy/docker_practice#454]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Linux
   * [x] CentOS 7
   * [x] Fedora
   * [x] Ubuntu 16.04 +
   * [x] Debian 9 +
* [x] macOS
* [x] Windows 10
* [x] Raspberry Pi (ARM)
* [x] Others (Pls describe below)

### Docker Version

* [x] Edge (v19.03)
* [x] Stable (v19.03)
* [x] 1.13.0 or Before

### Problem Description

![image](https://user-images.githubusercontent.com/26616875/86430341-984ee100-bd24-11ea-8e80-7c73d83d172d.png)

**Comment by khs1994** [comment]
已修复，请重新 pull 镜像并运行。

**Comment by khs1994** [comment]
基础镜像 nginx 更新引发的错误。
