### ISSUE TITLE
最新版本的 PDF

### ISSUE THREAD

**Issue by takeTrace** [yeasy/docker_practice#455]
我看了下载只有0.9版本的 PDF, 好像没有更新成最新的, 能不能提供下最新版本的 PDF ???

**Comment by khs1994** [comment]
@yeasy 由于迁移到新版 GitBook，网页端不再支持下载 PDF。可以考虑使用命令行工具自行生成。

https://www.jianshu.com/p/7d192b650874

**Comment by khs1994** [comment]
在 **看云** 点击 **下载** 按钮，选择类型（PDF）进行下载 

https://www.kancloud.cn/docker_practice/docker_practice
