### ISSUE TITLE
实战多阶段构建laravel镜像案例错误

### ISSUE THREAD

**Issue by hezhongjiang** [yeasy/docker_practice#465]
### Environment

*  macOS

### Docker Version

* [x] Stable (v19.03)

### Problem Description

文档案例错误

在 `使用镜像->Dockerfile多阶段构建中->实战多阶段构建laravel镜像`章节中，dockerfile在php部分有错误，导致镜像无法构建成功。

**Comment by khs1994** [comment]
可能 laravel 文件结构有变化

**Comment by hezhongjiang** [comment]
> 可能 laravel 文件结构有变化
不是，执行 `php artisan package:discover`，这个应该放到最后一行，创建完storeage目录后，再执行命令

**Comment by khs1994** [comment]
php artisan package:discover

这个命令只对 bootstrap/cache/packages.php文件有影响吧

**Comment by khs1994** [comment]
> 
> 
> > 可能 laravel 文件结构有变化
> 
> 不是，执行 `php artisan package:discover`，这个应该放到最后一行，创建完storeage目录后，再执行命令

是这个问题，同时进行更新适配 Laravel 8.x 文件结构。
