### ISSUE TITLE
一个字可能写错了

### ISSUE THREAD

**Issue by codeLearner000** [yeasy/docker_practice#501]
![image](https://user-images.githubusercontent.com/104556623/165884224-08b97c40-84e2-4850-8900-8f9e318218d9.png)

**Comment by insistcp** [comment]
您的邮件已安全到达目的地！
                  谢谢  陈鹏

**Comment by visionguo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yeasy** [comment]
内 --> "内的"？

**Comment by codeLearner000** [comment]
看不太懂，读起来怪怪的

**Comment by WaterAndBread** [comment]
谢谢，您的邮件已收到。祝您天天快乐！
