### ISSUE TITLE
有一个语句错误

### ISSUE THREAD

**Issue by reidzhou** [yeasy/docker_practice#506]
![image](https://user-images.githubusercontent.com/34478469/176585534-7f13adbd-c05a-44a2-982a-bf1410e22f60.png)

这里大概是想说：这些准备工作是和容器 CMD 无关的，无论 CMD 什么，都需要事先进行一个预处理的工作。

**Comment by insistcp** [comment]
您的邮件已安全到达目的地！
                  谢谢  陈鹏

**Comment by visionguo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by reidzhou** [comment]
> @reidzhou sure, would you like to make a quick commit to fix?

🍻  my pleasure!

**Comment by khs1994** [comment]
为（是）什么
