### ISSUE TITLE
安装k8s，配置阿里的repo后，yum install kubelet kubeadm kubectl时，报错：无法验证kubernetes的xml签名

### ISSUE THREAD

**Issue by L-960** [yeasy/docker_practice#509]
* [ ] Have u googled the problem? If no, pls do that first!

### Environment
* [x] Linux
   * [x] CentOS 7

### Docker Version

* [x] Docker CE 19.03.9

### Problem Description

按照步骤按照k8s，配置yum的k8s repo后，安装 kubelet kubeadm kubectl时，报错
完整错误如下：
==============begin================
[root@VM-4-3-centos etc]# sudo yum install -y kubelet kubeadm kubectl
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
docker-ce-stable                                                                                                                                                              | 3.5 kB  00:00:00     
epel                                                                                                                                                                          | 4.7 kB  00:00:00     
extras                                                                                                                                                                        | 2.9 kB  00:00:00     
kubernetes/signature                                                                                                                                                          |  844 B  00:00:00     
Retrieving key from https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg
Retrieving key from https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
kubernetes/signature                                                                                                                                                          | 1.4 kB  00:00:00 !!! 
https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
Trying other mirror.

 One of the configured repositories failed (Kubernetes),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=kubernetes ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable kubernetes
        or
            subscription-manager repos --disable=kubernetes

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=kubernetes.skip_if_unavailable=true

failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes

==============end================

### 解决方案
在上一步配置kubernetes.repo时，修改配置为：
$ cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
enabled=1
gpgcheck=0
repo_gpgcheck=0
gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
EOF

重新yum install，安装成功

**Comment by xiangjiu** [comment]
问一下那个 编辑此页 然后跳转到gitHub 怎么弄
