### ISSUE TITLE
image/dockerfile/onbuild.md 文档中  RUN 和 WORKDIR 优化

### ISSUE THREAD

**Issue by lvbibir** [yeasy/docker_practice#522]
### Environment

* [x] Linux
   * [x] CentOS 7

### Docker Version

* [x] Stable (v20.10)

### Problem Description

在 [Dockerfile-ONBUILD](https://yeasy.gitbook.io/docker_practice/image/dockerfile/onbuild) 教程中第一处演示代码中同时使用了 `RUN mkdir /app` 和 `WORKDIR /app` ，这里是否应该优化一下，删除掉 `RUN mkdir /app`

原代码：

```dockerfile
FROM node:slim
RUN mkdir /app
WORKDIR /app
COPY ./package.json /app
RUN [ "npm", "install" ]
COPY . /app/
CMD [ "npm", "start" ]
```

**Comment by yeasy** [comment]
`/app` does not exist in the image by default, and do not rely on workdir "magically" creating a directory.

**Comment by lvbibir** [comment]
If you use `workdir` to create a directory, what problems will it bring?
