### ISSUE TITLE
docker离线安装中，关于rpm离线下载、rpm离线本地安装的问题。

### ISSUE THREAD

**Issue by hellozrh** [yeasy/docker_practice#528]
### rpm离线下载
文档https://github.com/yeasy/docker_practice/blob/master/install/offline.md中列出的离线下载包方法
```bash
sudo yum install --downloadonly --downloaddir=/tmp/docker-19.03 docker-ce-19.03.8-3.el7 docker-ce-cli-19.03.8-3.el7 
```
如果联网机器已经安装过了当前版本，则会提示“软件包 ******** 已安装并且是最新版本”，导致无法下载。
![image](https://github.com/yeasy/docker_practice/assets/12250931/d6b9724c-33d0-49ae-8603-6e591a62ac0f)

### rpm离线本地安装
文档https://github.com/yeasy/docker_practice/blob/master/install/offline.md中列出的离线下载包方法
```bash
yum install *.rpm
```
因为依赖包先后顺序无法正确梳理，也会显示各种依赖问题导致安装失败。

**Comment by insistcp** [comment]
您的邮件已安全到达目的地！
                  谢谢  陈鹏

**Comment by visionguo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by visionguo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
