### ISSUE TITLE
关于bashrc_docker

### ISSUE THREAD

**Issue by trumanliu** [yeasy/docker_practice#53]
我在使用github上的bashrc脚本时docker-enter报出错误:
dirname: invalid option -- 'b'
Try 'dirname --help' for more information.
我在检查错误是发现此时$0为-bash,我把所有的$0替换成了$BASH_SOURCE[0]后问题解决了。我的环境为centos7,bash version:GNU bash, version 4.2.45(1)-release (x86_64-redhat-linux-gnu)

**Comment by yeasy** [comment]
从错误上看，应该是没有给定完整的bash路径造成的。
这里其实是获取bash命令所在的路径，$BASH_SOURCE[0] 的方法是否centos7独有的？我在Ubuntu系统中测试是不可行的。
另外，docker-enter 这种方式已经有了更好的替代，即 docker exec，推荐试试。

**Comment by trumanliu** [comment]
刚看了一下exec,而且大神们都教育我用docker进入容器的需求本身就是错的。我还要多学习。bash_sorce[0]的问题我看别人也遇到过,等有时间了深入研究下。anyway，非常感谢。
