### ISSUE TITLE
Raspbian Bullseye 上的安装方式与 教程所述 Buster 方式不尽兼容

### ISSUE THREAD

**Issue by RockChinQ** [yeasy/docker_practice#539]
* [x] Have u googled the problem? If no, pls do that first!

### Environment

* [x] Raspberry Pi (ARM) Bullseye

### Docker Version

* [x] Stable (v25.0.1)

### Problem Description

根据 Raspbian 上的[安装步骤](https://yeasy.gitbook.io/docker_practice/install/raspberry-pi)，执行到添加 APT 源时（使用境内阿里源），报错未找到合适分发模板

```bash
pi@raspberrypi:~/docker $ sudo add-apt-repository     "deb [arch=armhf] https://mirrors.aliyun.com/docker-ce/linux/raspbian \
    bullseye \
    stable"
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/bullseye
```
### Solution

手动编辑 `/etc/apt/sources.list` 后即可继续后续步骤

```
deb [arch=armhf] https://mirrors.aliyun.com/docker-ce/linux/raspbian bullseye stable
```

快捷命令

```bash
sudo echo "deb [arch=armhf] https://mirrors.aliyun.com/docker-ce/linux/raspbian bullseye stable" | sudo tee -a /etc/apt/sources.list
```

**Comment by visionguo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by insistcp** [comment]
您的邮件已安全到达目的地！
                  谢谢  陈鹏

**Comment by yeasy** [comment]
> * [x]  Have u googled the problem? If no, pls do that first!
> 
> ### Environment
> * [x]  Raspberry Pi (ARM) Bullseye
> 
> ### Docker Version
> * [x]  Stable (v25.0.1)
> 
> ### Problem Description
> 根据 Raspbian 上的[安装步骤](https://yeasy.gitbook.io/docker_practice/install/raspberry-pi)，执行到添加 APT 源时（使用境内阿里源），报错未找到合适分发模板
> 
> ```shell
> pi@raspberrypi:~/docker $ sudo add-apt-repository     "deb [arch=armhf] https://mirrors.aliyun.com/docker-ce/linux/raspbian \
>     bullseye \
>     stable"
> Traceback (most recent call last):
>   File "/usr/bin/add-apt-repository", line 95, in <module>
>     sp = SoftwareProperties(options=options)
>   File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
>     self.reload_sourceslist()
>   File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
>     self.distro.get_sources(self.sourceslist)    
>   File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
>     raise NoDistroTemplateException(
> aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/bullseye
> ```
> 
> ### Solution
> 手动编辑 `/etc/apt/sources.list` 后即可继续后续步骤
> 
> ```
> deb [arch=armhf] https://mirrors.aliyun.com/docker-ce/linux/raspbian bullseye stable
> ```
> 
> 快捷命令
> 
> ```shell
> sudo echo "deb [arch=armhf] https://mirrors.aliyun.com/docker-ce/linux/raspbian bullseye stable" | sudo tee -a /etc/apt/sources.list
> ```

Thanks! Would you like to contribute the change with a PR?
