### ISSUE TITLE
docker_practice/README.md 内容重复

### ISSUE THREAD

**Issue by donhui** [yeasy/docker_practice#64]
Docker 是个伟大的项目，它彻底释放了虚拟化的威力，极大降低了云计算资源供应的成本，同时让应用的分发、测试、部署和分发都变得前所未有的高效和轻松

上面的内容中，分发出现了两次：【同时让应用的分发、测试、部署和分发都变得前所未有的高效和轻松】

**Comment by yeasy** [comment]
thanks, will fix it.
