### ISSUE TITLE
可以看到自定义命名的容器，db 和 web，db 容器的 names 列有 db 也有 web/db。

### ISSUE THREAD

**Issue by qiaoyan** [yeasy/docker_practice#78]
实测并没有， ubuntu 14.04, docker 1.8.3
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS
                                                                  NAMES
e4fb617479de        training/webapp       "python app.py"          11 seconds ago      Up 11 seconds       0.0.0.0:32768->5000/tcp                                                web

83670d28a9d0        training/postgres     "su postgres -c '/usr"   36 seconds ago      Up 35 seconds       5432/tcp                                                               db
-----------------
http://dockerpool.com/static/books/docker_practice/network/linking.html

**Comment by yeasy** [comment]
db 容器要先创建，然后创建 web 容器 link 过去。

**Comment by khs1994** [comment]
`--link` 已经废弃 #215
