### ISSUE TITLE
关于创建image的一段描述

### ISSUE THREAD

**Issue by xusiwei** [yeasy/docker_practice#82]
```
$ sudo docker run -t -i training/sinatra /bin/bash
root@0b2616b0e5a8:/# gem install json
```
> 当结束后，我们使用 exit 来退出，现在我们的容器已经被我们改变了，使用 docker commit 命令来提交更新后的副本。

用exit退出container里的bash会话，这个container也就结束了，后面commit时候指定container id已经不能用了。

应该是另外打开一个终端执行commit吧？

**Comment by yeasy** [comment]
The commit command is running at host.
